const enc=encodeURIComponent;let scope='all',lastQuery='';
const sources=[['Project Gutenberg','archive',q=>`https://www.gutenberg.org/ebooks/search/?query=${enc(q)}`],['Library of Congress','archive',q=>`https://www.loc.gov/search/?q=${enc(q)}`],['Internet Archive','archive',q=>`https://archive.org/search?query=${enc(q)}`],['Biodiversity Heritage Library','archive',q=>`https://www.biodiversitylibrary.org/search?searchTerm=${enc(q)}&stype=F#/titles`],['DOAB','research',q=>`https://directory.doabooks.org/discover?query=${enc(q)}`],['U.S. National Archives','government',q=>`https://catalog.archives.gov/search?q=${enc(q)}`],['GovInfo','government',q=>`https://www.govinfo.gov/app/search/${enc(q)}`],['FOIA.gov','government',q=>`https://www.google.com/search?q=${enc('site:foia.gov '+q)}`],['Data.gov','science',q=>`https://catalog.data.gov/dataset/?q=${enc(q)}`],['Google Patents','research',q=>`https://patents.google.com/?q=${enc(q)}`],['Crossref','research',q=>`https://search.crossref.org/?q=${enc(q)}`],['OpenAlex','research',q=>`https://openalex.org/works?page=1&filter=default.search:${enc(q)}`],['PubMed','research',q=>`https://pubmed.ncbi.nlm.nih.gov/?term=${enc(q)}`],['arXiv','research',q=>`https://arxiv.org/search/?query=${enc(q)}&searchtype=all`],['WorldCat','archive',q=>`https://search.worldcat.org/search?q=${enc(q)}`],['Europeana','archive',q=>`https://www.europeana.eu/en/search?query=${enc(q)}`],['DPLA','archive',q=>`https://dp.la/search?q=${enc(q)}`],['Smithsonian','archive',q=>`https://www.si.edu/search?edan_q=${enc(q)}`],['Trove / NLA','archive',q=>`https://trove.nla.gov.au/search?keyword=${enc(q)}`],['Zenodo','research',q=>`https://zenodo.org/search?q=${enc(q)}`],['CORE','research',q=>`https://core.ac.uk/search?q=${enc(q)}`],['ClinicalTrials.gov','research',q=>`https://clinicaltrials.gov/search?term=${enc(q)}`],['PubChem','science',q=>`https://pubchem.ncbi.nlm.nih.gov/#query=${enc(q)}`],['NASA Earthdata','science',q=>`https://search.earthdata.nasa.gov/search?q=${enc(q)}`],['USGS ScienceBase','science',q=>`https://www.sciencebase.gov/catalog/items?q=${enc(q)}`],['DataCite','research',q=>`https://commons.datacite.org/?query=${enc(q)}`],['Europe PMC','research',q=>`https://europepmc.org/search?query=${enc(q)}`]];
const wings=['Physics & Mathematics','Astronomy & Cosmology','Engineering & Technology','Chemistry & Materials','Biology & Ecology','Earth & Planetary Science','Climate & Atmosphere','Ocean Science','Medicine & Public Health','History & Archaeology','Anthropology & Civilization','Government, Law & FOIA','Economics & Demographics','Patents & Inventions','Maps & Geography','Interdisciplinary Research'];
const observatories=[['Space & Astronomy','https://science.nasa.gov/'],['Solar & Space Weather','https://www.swpc.noaa.gov/'],['Earth & Satellite','https://www.earthdata.nasa.gov/'],['Weather & Atmosphere','https://www.weather.gov/'],['Climate','https://www.ncei.noaa.gov/'],['Ocean','https://oceanservice.noaa.gov/'],['Geology & Seismic','https://earthquake.usgs.gov/'],['Biodiversity & Ecology','https://www.gbif.org/'],['Volcanoes','https://volcano.si.edu/'],['Near-Earth Objects','https://cneos.jpl.nasa.gov/'],['Solar System Dynamics','https://ssd.jpl.nasa.gov/'],['Global Earth Observation','https://www.copernicus.eu/']];
function classify(q){if(extractDOI(q))return['DOI / scholarly record','research'];if(/patent|\bus\s?\d{6,}/i.test(q))return['Patent / technical record','research'];if(isQuoted(q))return['Exact quotation / phrase trace','archive'];if(/foia|congress|law|statute|agency|government|public record/i.test(q))return['Government / public record','government'];if(/physics|biology|chemistry|climate|orbit|earthquake|dataset|astronomy|science|trial|medicine|health|journal|paper|study|doi/i.test(q))return['Scientific research','science'];if(/history|historical|archive|war|ancient|president/i.test(q))return['Historical / archival research','archive'];return['General cross-archive discovery','all']}
const esc=x=>String(x==null?'':x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=u=>/^https?:\/\//i.test(String(u||''))?String(u):'#';
const tokens=s=>String(s||'').toLowerCase().match(/[a-z0-9]{2,}/g)||[];
const normalizeTitle=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,' ').trim();
const isQuoted=q=>/^\s*["“].+["”]\s*$/.test(String(q||''));
function extractDOI(q){const m=String(q||'').match(/10\.\d{4,9}\/[-._;()/:A-Z0-9]+/i);return m?m[0].replace(/[).,;]+$/,''):''}
function scoreResult(r,q){const phrase=String(q||'').trim().replace(/^["“]|["”]$/g,'').toLowerCase(),qt=tokens(phrase),title=String(r.title||'').toLowerCase(),detail=String(r.detail||'').toLowerCase();let s=0;if(title===phrase)s+=60;if(phrase&&title.includes(phrase))s+=32;qt.forEach(t=>{if(title.includes(t))s+=7;if(detail.includes(t))s+=2});if(r.doi)s+=5;if(r.confirmations>1)s+=(r.confirmations-1)*8;if(r.openAccess===true)s+=3;return s}
function canonicalKey(r){const doi=String(r.doi||'').toLowerCase().replace(/^https?:\/\/(dx\.)?doi\.org\//,'').trim();if(doi)return'doi:'+doi;const t=normalizeTitle(r.title);return t?'title:'+t.slice(0,180):''}
function mergeResults(items){const map=new Map();for(const r of items){const k=canonicalKey(r);if(!k)continue;if(!map.has(k)){map.set(k,{...r,sources:[r.source],confirmations:1});continue}const x=map.get(k);if(!x.sources.includes(r.source))x.sources.push(r.source);x.confirmations=x.sources.length;if((!x.detail||String(r.detail||'').length>String(x.detail||'').length)&&r.detail)x.detail=r.detail;if(!x.doi&&r.doi)x.doi=r.doi;if(!x.year&&r.year)x.year=r.year;if((!x.url||x.url==='#')&&r.url)x.url=r.url;if(r.openAccess===true)x.openAccess=true;x.source=x.sources.join(' + ')}return [...map.values()]}
function card(r){const meta=[r.year,r.doi,r.confirmations>1?`${r.confirmations} sources confirm`:null,r.openAccess===true?'open access':null].filter(Boolean).join(' · ');return `<a target="_blank" rel="noopener" href="${esc(safeUrl(r.url))}"><small>${esc(r.source)} · ${esc(r.type||'RESULT')}</small><h3>${esc(r.title||'Untitled')}</h3>${meta?`<small>${esc(meta)}</small>`:''}${r.detail?`<p>${esc(r.detail).slice(0,320)}</p>`:''}<span>Open original →</span></a>`}
async function getJSON(url,ms=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:'application/json'}});if(!r.ok)throw new Error(String(r.status));return await r.json()}finally{clearTimeout(t)}}
const adapters=[
{name:'Project Gutenberg',cat:'archive',run:async q=>{const d=await getJSON(`https://gutendex.com/books?search=${enc(q)}`);return(d.results||[]).slice(0,10).map(x=>({source:'Project Gutenberg',type:'BOOK',title:x.title,detail:(x.authors||[]).map(a=>a.name).join(', '),url:`https://www.gutenberg.org/ebooks/${x.id}`}))}},
{name:'Library of Congress',cat:'archive',run:async q=>{const d=await getJSON(`https://www.loc.gov/search/?q=${enc(q)}&fo=json&c=10`);return(d.results||[]).slice(0,10).map(x=>({source:'Library of Congress',type:Array.isArray(x.type)?x.type[0]:(x.type||'RECORD'),title:x.title,detail:Array.isArray(x.description)?x.description[0]:(x.description||x.date||''),year:x.date||'',url:x.id||x.url}))}},
{name:'Internet Archive',cat:'archive',run:async q=>{const term=isQuoted(q)?`\"${String(q).trim().replace(/^["“]|["”]$/g,'')}\"`:q;const d=await getJSON(`https://archive.org/advancedsearch.php?q=${enc(term)}&fl[]=identifier,title,creator,year&rows=10&page=1&output=json`);return(d.response&&d.response.docs||[]).map(x=>({source:'Internet Archive',type:'ARCHIVE',title:x.title||x.identifier,detail:Array.isArray(x.creator)?x.creator.join(', '):(x.creator||''),year:x.year||'',url:`https://archive.org/details/${enc(x.identifier)}`}))}},
{name:'Crossref',cat:'research',run:async q=>{const doi=extractDOI(q);if(doi){const d=await getJSON(`https://api.crossref.org/works/${enc(doi)}`),x=d.message||{};return[{source:'Crossref',type:x.type||'SCHOLARLY',title:Array.isArray(x.title)?x.title[0]:(x.title||doi),detail:(x.author||[]).slice(0,4).map(a=>[a.given,a.family].filter(Boolean).join(' ')).join(', '),doi:x.DOI||doi,year:x.published&&x.published['date-parts']&&x.published['date-parts'][0]&&x.published['date-parts'][0][0],url:x.URL||`https://doi.org/${doi}`}]}const d=await getJSON(`https://api.crossref.org/works?query.bibliographic=${enc(q)}&rows=12`);return(d.message&&d.message.items||[]).map(x=>({source:'Crossref',type:x.type||'SCHOLARLY',title:Array.isArray(x.title)?x.title[0]:(x.title||x.DOI),detail:(x.author||[]).slice(0,4).map(a=>[a.given,a.family].filter(Boolean).join(' ')).join(', '),doi:x.DOI||'',year:x.published&&x.published['date-parts']&&x.published['date-parts'][0]&&x.published['date-parts'][0][0],url:x.URL||`https://doi.org/${x.DOI}`}))}},
{name:'OpenAlex',cat:'research',run:async q=>{const d=await getJSON(`https://api.openalex.org/works?search=${enc(q)}&per-page=12`);return(d.results||[]).map(x=>({source:'OpenAlex',type:x.type||'RESEARCH',title:x.display_name,detail:(x.authorships||[]).slice(0,4).map(a=>a.author&&a.author.display_name).filter(Boolean).join(', '),doi:x.doi?String(x.doi).replace('https://doi.org/',''):'',year:x.publication_year||'',openAccess:!!(x.open_access&&x.open_access.is_oa),url:x.doi||(x.primary_location&&x.primary_location.landing_page_url)||x.id}))}},
{name:'PubMed',cat:'research',run:async q=>{const d=await getJSON(`https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=${enc(q)}&retmode=json&retmax=12`);const ids=d.esearchresult&&d.esearchresult.idlist||[];if(!ids.length)return[];const s=await getJSON(`https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&id=${ids.join(',')}&retmode=json`);return ids.map(id=>{const z=s.result&&s.result[id]||{};return{source:'PubMed',type:'MEDICINE',title:z.title||`PubMed ${id}`,detail:(z.authors||[]).slice(0,4).map(a=>a.name).join(', '),year:z.pubdate||'',url:`https://pubmed.ncbi.nlm.nih.gov/${id}/`}})}},
{name:'Data.gov',cat:'science',run:async q=>{const d=await getJSON(`https://catalog.data.gov/api/3/action/package_search?q=${enc(q)}&rows=10`);return(d.result&&d.result.results||[]).map(x=>({source:'Data.gov',type:'DATASET',title:x.title||x.name,detail:x.notes||'',year:x.metadata_modified?String(x.metadata_modified).slice(0,10):'',url:`https://catalog.data.gov/dataset/${x.name}`}))}},
{name:'ClinicalTrials.gov',cat:'research',run:async q=>{const d=await getJSON(`https://clinicaltrials.gov/api/v2/studies?query.term=${enc(q)}&pageSize=10&format=json`);return(d.studies||[]).map(x=>{const p=x.protocolSection||{},id=p.identificationModule||{},c=p.conditionsModule||{},s=p.statusModule||{};return{source:'ClinicalTrials.gov',type:'CLINICAL TRIAL',title:id.briefTitle||id.officialTitle||id.nctId,detail:[(c.conditions||[]).join(', '),s.overallStatus].filter(Boolean).join(' · '),year:s.startDateStruct&&s.startDateStruct.date||'',url:`https://clinicaltrials.gov/study/${id.nctId}`}})}},
{name:'NASA Earthdata',cat:'science',run:async q=>{const d=await getJSON(`https://cmr.earthdata.nasa.gov/search/collections.json?keyword=${enc(q)}&page_size=10`);return(d.feed&&d.feed.entry||[]).map(x=>{const link=(x.links||[]).find(l=>l&&l.href&&/^https?:/i.test(l.href));return{source:'NASA Earthdata',type:'EARTH DATA',title:x.title||x.short_name,detail:x.summary||'',year:x.time_start?String(x.time_start).slice(0,10):'',url:link&&link.href||`https://search.earthdata.nasa.gov/search?q=${enc(q)}`}})}},
{name:'Zenodo',cat:'research',run:async q=>{const d=await getJSON(`https://zenodo.org/api/records?q=${enc(q)}&size=10`);return(d.hits&&d.hits.hits||[]).map(x=>({source:'Zenodo',type:(x.metadata&&x.metadata.resource_type&&x.metadata.resource_type.title)||'RESEARCH RECORD',title:x.metadata&&x.metadata.title||`Zenodo ${x.id}`,detail:((x.metadata&&x.metadata.creators)||[]).slice(0,4).map(a=>a.name).join(', '),doi:x.doi||'',openAccess:true,year:x.created?String(x.created).slice(0,10):'',url:(x.links&&x.links.html)||`https://zenodo.org/records/${x.id}`}))}},
{name:'DataCite',cat:'research',run:async q=>{const doi=extractDOI(q),url=doi?`https://api.datacite.org/dois/${enc(doi)}`:`https://api.datacite.org/dois?query=${enc(q)}&page[size]=12`;const d=await getJSON(url);const rows=Array.isArray(d.data)?d.data:(d.data?[d.data]:[]);return rows.map(x=>{const a=x.attributes||{},titles=a.titles||[],creators=a.creators||[];return{source:'DataCite',type:(a.types&&a.types.resourceTypeGeneral)||'RESEARCH',title:(titles[0]&&titles[0].title)||a.doi||x.id,detail:creators.slice(0,4).map(c=>c.name||[c.givenName,c.familyName].filter(Boolean).join(' ')).join(', '),doi:a.doi||x.id||'',year:a.publicationYear||'',url:a.url||`https://doi.org/${a.doi||x.id}`}})}},
{name:'Europe PMC',cat:'research',run:async q=>{const d=await getJSON(`https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=${enc(q)}&format=json&pageSize=12`);return(d.resultList&&d.resultList.result||[]).map(x=>({source:'Europe PMC',type:x.pubType||'BIOMEDICAL',title:x.title||x.id,detail:[x.authorString,x.journalTitle].filter(Boolean).join(' · '),doi:x.doi||'',year:x.pubYear||'',openAccess:x.isOpenAccess==='Y',url:x.doi?`https://doi.org/${x.doi}`:`https://europepmc.org/article/${enc(x.source||'MED')}/${enc(x.id)}`}))}}
];
function launchers(q,hint){const ranked=sources.map(s=>({s,score:(s[1]===hint?3:0)+(scope==='all'||s[1]===scope?2:-5)})).filter(x=>x.score>=0).sort((a,b)=>b.score-a.score);return `<div style="grid-column:1/-1"><p class="eyebrow">FULL SOURCE NETWORK</p><p>Direct authoritative searches remain available below for sources that cannot safely expose live browser results.</p></div>`+ranked.map(x=>`<a target="_blank" rel="noopener" href="${esc(x.s[2](q))}"><small>${esc(x.s[1].toUpperCase())}</small><h3>${esc(x.s[0])}</h3><span>Open source search →</span></a>`).join('')}
async function searchAll(q){q=String(q||'').trim();if(!q)return;lastQuery=q;const [intent,hint]=classify(q),out=document.querySelector('#results'),status=document.querySelector('#intent');status.textContent=`Detected: ${intent}. Searching federated research network…`;out.innerHTML='<article><small>SEARCH ALL</small><h3>Searching connected collections…</h3><p>Collecting records from archives, scholarly indexes, clinical research, government data and Earth science.</p></article>';const active=scope==='all'?adapters:adapters.filter(a=>a.cat===scope||(scope==='science'&&a.cat==='research'));const settled=await Promise.allSettled(active.map(a=>a.run(q)));let raw=[];settled.forEach((x,i)=>{if(x.status==='fulfilled'&&Array.isArray(x.value))raw.push(...x.value.map(r=>({...r,_adapter:active[i].name})))});const results=mergeResults(raw);results.forEach(r=>r._score=scoreResult(r,q));results.sort((a,b)=>b._score-a._score||String(a.title).localeCompare(String(b.title)));const ok=settled.filter(x=>x.status==='fulfilled').length,fail=active.length-ok,confirmed=results.filter(r=>r.confirmations>1).length;status.textContent=`${intent} · ${results.length} ranked records · ${confirmed} cross-source confirmations · ${ok}/${active.length} live connectors responded${fail?` · ${fail} unavailable`:''}.`;out.innerHTML=(results.length?`<div style="grid-column:1/-1"><p class="eyebrow">RANKED LIVE RESULTS</p><p>Results are merged by DOI/title, deduplicated, relevance-ranked and cross-source confirmations are surfaced.</p></div>${results.map(card).join('')}`:'<article><h3>No inline matches returned</h3><p>The full source network remains below with your query preloaded.</p></article>')+launchers(q,hint)}
function boot(){const form=document.querySelector('#searchForm'),q=document.querySelector('#q');if(form&&q)form.addEventListener('submit',e=>{e.preventDefault();searchAll(q.value)});document.querySelectorAll('#scopes button').forEach(b=>{b.type='button';b.addEventListener('click',()=>{scope=b.dataset.scope||'all';document.querySelectorAll('#scopes button').forEach(x=>x.classList.toggle('active',x===b));if(lastQuery)searchAll(lastQuery)})});const src=document.querySelector('#sources');if(src)src.innerHTML=sources.map(s=>`<article><small>${esc(s[1].toUpperCase())}</small><h3>${esc(s[0])}</h3><p>Connected authoritative discovery source.</p></article>`).join('');const wg=document.querySelector('#wings');if(wg){wg.innerHTML=wings.map(w=>`<button type="button">${esc(w)}</button>`).join('');wg.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{q.value=b.textContent;scope='all';searchAll(b.textContent)}))}const ob=document.querySelector('#obs');if(ob)ob.innerHTML=observatories.map(o=>`<a target="_blank" rel="noopener" href="${esc(o[1])}"><small>LIVE SOURCE</small><h3>${esc(o[0])}</h3><span>Open observatory →</span></a>`).join('');const refresh=document.querySelector('#refreshQuakes');if(refresh)refresh.addEventListener('click',quakes);const cv=document.querySelector('#convert');if(cv)cv.addEventListener('click',convertUnits);const orb=document.querySelector('#orbit');if(orb)orb.addEventListener('click',orbitCalc);const rl=document.querySelector('#researchLaunch');if(rl)rl.addEventListener('click',()=>searchAll(lastQuery||q.value||'open science'));quakes()}
async function quakes(){const state=document.querySelector('#quakeState');if(!state)return;state.textContent='LOADING';try{const d=await getJSON('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson'),fs=d.features||[];let max=null;fs.forEach(x=>{if(!max||Number(x.properties&&x.properties.mag)>Number(max.properties&&max.properties.mag))max=x});const count=document.querySelector('#quakeCount'),mx=document.querySelector('#quakeMax');if(count)count.textContent=fs.length;if(mx)mx.textContent=max?`M${max.properties.mag} · ${max.properties.place}`:'None';state.textContent='LIVE · '+new Date(d.metadata.generated).toLocaleTimeString()}catch(e){state.textContent='SOURCE UNAVAILABLE'}}
function convertUnits(){const meters={m:1,km:1000,mi:1609.344,ft:.3048},v=Number(document.querySelector('#unitValue').value),f=document.querySelector('#unitFrom').value,t=document.querySelector('#unitTo').value;document.querySelector('#unitOut').textContent=`${v*meters[f]/meters[t]} ${t}`}
function orbitCalc(){const M=Number(document.querySelector('#mass').value),r=Number(document.querySelector('#radius').value),v=Math.sqrt(6.67430e-11*M/r);document.querySelector('#orbitOut').textContent=Number.isFinite(v)?`${v.toLocaleString()} m/s`:'Check inputs'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
