import * as maplibregl from 'https://unpkg.com/maplibre-gl@6.6.0/dist/maplibre-gl.mjs';
const $=s=>document.querySelector(s);let map;
const utcDate=(offset=0)=>new Date(Date.now()+offset*86400000).toISOString().slice(0,10);
const nasaDate=utcDate(0);
const gibs=(layer,date=nasaDate)=>`https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/${layer}/default/${date}/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg`;
const style={version:8,sources:{imagery:{type:'raster',tiles:['https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19,attribution:'Imagery © Esri, Maxar, Earthstar Geographics, and the GIS User Community'},clouds:{type:'raster',tiles:[gibs('VIIRS_SNPP_CorrectedReflectance_TrueColor')],tileSize:256,minzoom:0,maxzoom:9,attribution:'NASA EOSDIS GIBS / Suomi NPP VIIRS'},labels:{type:'raster',tiles:['https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19},terrain:{type:'raster-dem',tiles:['https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png'],tileSize:256,maxzoom:15,encoding:'terrarium'}},layers:[{id:'space',type:'background',paint:{'background-color':'#01070b'}},{id:'satellite',type:'raster',source:'imagery',paint:{'raster-opacity':1,'raster-saturation':.08,'raster-contrast':.08}},{id:'nasa-cloud-observation',type:'raster',source:'clouds',paint:{'raster-opacity':['interpolate',['linear'],['zoom'],0,.82,2,.78,4,.68,6,.48,8,.22,10,0],'raster-saturation':.03,'raster-contrast':.08,'raster-fade-duration':350}},{id:'labels',type:'raster',source:'labels',paint:{'raster-opacity':['interpolate',['linear'],['zoom'],0,0,2,0,3,.08,5,.42,8,.72,12,.94]}}]};
const status=t=>{const e=$('#providerState');if(e)e.textContent=t};
try{map=new maplibregl.Map({container:'earthMapStable',style,center:[0,15],zoom:1.15,minZoom:.35,maxZoom:19,pitch:0,bearing:0,renderWorldCopies:false,antialias:true,attributionControl:true});map.addControl(new maplibregl.NavigationControl(),'top-right');map.once('load',()=>{map.setProjection({type:'globe'});try{map.setTerrain({source:'terrain',exaggeration:1.12});map.setFog({range:[.4,8],color:'#8bb7c8','horizon-blend':.12,'high-color':'#0d3550','space-color':'#000207','star-intensity':.18})}catch(e){}status(`Geographical Earth · NASA VIIRS near-real-time daily composite ${nasaDate} over stable 3D globe`)});map.on('error',e=>{const msg=e?.error?.message||'resource error';if(String(msg).includes('VIIRS')||String(msg).includes('gibs'))status(`Geographical Earth · NASA cloud layer loading notice · ${msg}`)});}catch(e){status(`Geographical Earth initialization error · ${e.message}`)}
$('#resetEarth')?.addEventListener('click',()=>map?.easeTo({center:[0,15],zoom:1.15,pitch:0,bearing:0,duration:400}));
$('#refreshEarth')?.addEventListener('click',()=>{status(`Refreshing NASA satellite cloud observation · ${nasaDate}`);map?.triggerRepaint()});
$('#locateMe')?.addEventListener('click',()=>navigator.geolocation?.getCurrentPosition(p=>map?.flyTo({center:[p.coords.longitude,p.coords.latitude],zoom:10,pitch:55,duration:900}),()=>status('Location unavailable.')));
