import * as maplibregl from 'https://unpkg.com/maplibre-gl@6.6.0/dist/maplibre-gl.mjs';
const $=s=>document.querySelector(s);let map;
const now=new Date();now.setUTCSeconds(0,0);now.setUTCMinutes(Math.floor(now.getUTCMinutes()/10)*10-20);const liveTime=now.toISOString().replace('.000','');
const day=liveTime.slice(0,10);
const wmts=(layer,time,ext='png')=>`https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/${layer}/default/${time}/GoogleMapsCompatible_Level6/{z}/{y}/{x}.${ext}`;
const daily=(layer)=>`https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/${layer}/default/${day}/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg`;
const style={version:8,sources:{imagery:{type:'raster',tiles:['https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19,attribution:'Imagery © Esri, Maxar, Earthstar Geographics, and the GIS User Community'},viirs:{type:'raster',tiles:[daily('VIIRS_SNPP_CorrectedReflectance_TrueColor')],tileSize:256,minzoom:0,maxzoom:9,attribution:'NASA EOSDIS GIBS / VIIRS'},goesEast:{type:'raster',tiles:[wmts('GOES-East_ABI_GeoColor',liveTime)],tileSize:256,minzoom:0,maxzoom:6,attribution:'NASA EOSDIS GIBS / NOAA GOES-East ABI'},goesWest:{type:'raster',tiles:[wmts('GOES-West_ABI_GeoColor',liveTime)],tileSize:256,minzoom:0,maxzoom:6,attribution:'NASA EOSDIS GIBS / NOAA GOES-West ABI'},labels:{type:'raster',tiles:['https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19},terrain:{type:'raster-dem',tiles:['https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png'],tileSize:256,maxzoom:15,encoding:'terrarium'}},layers:[{id:'space',type:'background',paint:{'background-color':'#01070b'}},{id:'satellite',type:'raster',source:'imagery',paint:{'raster-opacity':1,'raster-saturation':.05,'raster-contrast':.05}},{id:'global-observation',type:'raster',source:'viirs',paint:{'raster-opacity':['interpolate',['linear'],['zoom'],0,.62,3,.56,6,.35,9,0]}},{id:'goes-west-live',type:'raster',source:'goesWest',paint:{'raster-opacity':['interpolate',['linear'],['zoom'],0,.94,3,.9,6,.6,9,0],'raster-fade-duration':0}},{id:'goes-east-live',type:'raster',source:'goesEast',paint:{'raster-opacity':['interpolate',['linear'],['zoom'],0,.94,3,.9,6,.6,9,0],'raster-fade-duration':0}},{id:'labels',type:'raster',source:'labels',paint:{'raster-opacity':['interpolate',['linear'],['zoom'],0,0,2,0,3,.08,5,.42,8,.72,12,.94]}}]};
const status=t=>{const e=$('#providerState');if(e)e.textContent=t};
try{map=new maplibregl.Map({container:'earthMapStable',style,center:[-35,12],zoom:1.05,minZoom:.35,maxZoom:19,pitch:0,bearing:0,renderWorldCopies:false,antialias:true,attributionControl:true});map.addControl(new maplibregl.NavigationControl(),'top-right');map.once('load',()=>{map.setProjection({type:'globe'});try{map.setTerrain({source:'terrain',exaggeration:1.12});map.setFog({range:[.4,8],color:'#8bb7c8','horizon-blend':.12,'high-color':'#0d3550','space-color':'#000207','star-intensity':.18})}catch(e){}status(`Geographical Earth · GOES live observation ${liveTime} · VIIRS global fallback ${day}`)});map.on('error',()=>{});}catch(e){status(`Geographical Earth initialization error · ${e.message}`)}
$('#resetEarth')?.addEventListener('click',()=>map?.easeTo({center:[-35,12],zoom:1.05,pitch:0,bearing:0,duration:400}));
$('#refreshEarth')?.addEventListener('click',()=>location.reload());
$('#locateMe')?.addEventListener('click',()=>navigator.geolocation?.getCurrentPosition(p=>map?.flyTo({center:[p.coords.longitude,p.coords.latitude],zoom:10,pitch:55,duration:900}),()=>status('Location unavailable.')));
