import * as maplibregl from 'https://unpkg.com/maplibre-gl@6.6.0/dist/maplibre-gl.mjs';

const $=s=>document.querySelector(s);
const records=[];
const recordKeys=new Set();
const sourceStates=new Map();
let map=null;
let googleMap=null;
let googleLayer=null;
let googleMarkers=[];
let earthImageryVisible=true;
const colorFor={earthquake:'#5ae5ff',hazard:'#ffd43b',station:'#36e58b',alert:'#ff536f'};
const NASA_BLUE_MARBLE_WMS='https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=BlueMarble_ShadedRelief_Bathymetry&STYLES=&FORMAT=image/jpeg&TRANSPARENT=FALSE&SRS=EPSG:3857&WIDTH=256&HEIGHT=256&BBOX={bbox-epsg-3857}';

function validLatLon(lat,lon){return Number.isFinite(Number(lat))&&Number.isFinite(Number(lon))&&Number(lat)>=-90&&Number(lat)<=90&&Number(lon)>=-180&&Number(lon)<=180}
function safeText(v){return String(v==null?'':v)}
function escapeHtml(v){return safeText(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function withTimeout(ms=12000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),ms);return{signal:controller.signal,done:()=>clearTimeout(timer)}}
async function getJSON(url,ms=12000){const t=withTimeout(ms);try{const r=await fetch(url,{signal:t.signal,cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return await r.json()}finally{t.done()}}
async function getText(url,ms=12000){const t=withTimeout(ms);try{const r=await fetch(url,{signal:t.signal,cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return await r.text()}finally{t.done()}}

function addRecord(r){
  if(!r||!validLatLon(r.lat,r.lon))return false;
  const id=safeText(r.id||`${r.source}:${r.lat}:${r.lon}`);
  const key=`${id}|${Number(r.lat).toFixed(6)}|${Number(r.lon).toFixed(6)}`;
  if(recordKeys.has(key))return false;
  recordKeys.add(key);
  records.push({id,source:safeText(r.source||'Unknown'),type:r.type||'station',title:safeText(r.title||r.source||'Observation'),lat:Number(r.lat),lon:Number(r.lon),time:r.time||null,url:r.url||null,detail:safeText(r.detail||'')});
  return true;
}
function clearRecords(){records.length=0;recordKeys.clear()}
function setSource(id,label,state,count=0,detail=''){sourceStates.set(id,{label,state,count,detail});renderSourceFabric()}
function renderSourceFabric(){
  const box=$('#sourceFabric');
  if(!box)return;
  box.innerHTML=[...sourceStates.values()].map(s=>`<article class="source-card"><div><strong>${escapeHtml(s.label)}</strong><span>${escapeHtml(s.detail)}</span></div><b class="source-${escapeHtml(String(s.state).toLowerCase())}">${escapeHtml(s.state)}${Number.isFinite(Number(s.count))?` · ${Number(s.count).toLocaleString()}`:''}</b></article>`).join('');
}
function toGeoJSON(){return{type:'FeatureCollection',features:records.map(r=>({type:'Feature',id:r.id,geometry:{type:'Point',coordinates:[r.lon,r.lat]},properties:{id:r.id,source:r.source,type:r.type,title:r.title,time:r.time||'',url:r.url||'',detail:r.detail}}))}}
function updateMap(){if(!map)return;const src=map.getSource('dom-observations');if(src)src.setData(toGeoJSON());updateGoogleMarkers()}
function installObservationLayers(){if(!map.getSource('dom-observations'))map.addSource('dom-observations',{type:'geojson',data:toGeoJSON(),cluster:true,clusterMaxZoom:5,clusterRadius:36});if(!map.getLayer('dom-observation-clusters'))map.addLayer({id:'dom-observation-clusters',type:'circle',source:'dom-observations',filter:['has','point_count'],paint:{'circle-color':'#28485a','circle-radius':['step',['get','point_count'],13,100,17,1000,22],'circle-stroke-color':'#baf4ff','circle-stroke-width':1}});if(!map.getLayer('dom-observations'))map.addLayer({id:'dom-observations',type:'circle',source:'dom-observations',filter:['!',['has','point_count']],paint:{'circle-color':['match',['get','type'],'earthquake',colorFor.earthquake,'hazard',colorFor.hazard,'alert',colorFor.alert,colorFor.station],'circle-radius':['match',['get','type'],'earthquake',5,'hazard',6,'alert',6,4],'circle-stroke-color':'#071318','circle-stroke-width':1.2}})}
function installEarthImagery(){if(!map||map.getSource('dom-earth-imagery'))return;map.addSource('dom-earth-imagery',{type:'raster',tiles:[NASA_BLUE_MARBLE_WMS],tileSize:256,attribution:'NASA EOSDIS GIBS · Blue Marble'});const firstSymbol=map.getStyle().layers.find(l=>l.type==='symbol');map.addLayer({id:'dom-earth-imagery-layer',type:'raster',source:'dom-earth-imagery',paint:{'raster-opacity':.92}},firstSymbol?.id);earthImageryVisible=true;const b=$('#earthImagery');if(b)b.textContent='Earth imagery: ON'}
function toggleEarthImagery(){earthImageryVisible=!earthImageryVisible;if(map?.getLayer('dom-earth-imagery-layer'))map.setLayoutProperty('dom-earth-imagery-layer','visibility',earthImageryVisible?'visible':'none');const b=$('#earthImagery');if(b)b.textContent=`Earth imagery: ${earthImageryVisible?'ON':'OFF'}`;const s=$('#providerState');if(s)s.textContent=earthImageryVisible?'NASA Blue Marble geographic Earth active · source-backed D.O.M. observations remain anchored by latitude/longitude. Baseline imagery is not live.':'Earth imagery hidden · geographic labels and source-backed observations remain active.'}

async function pollUSGS(){const id='usgs';setSource(id,'USGS earthquakes','LOADING',0,'M2.5+ · past day');try{const j=await getJSON('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson');let n=0;for(const f of j.features||[]){const c=f?.geometry?.coordinates;if(!Array.isArray(c)||!validLatLon(c[1],c[0]))continue;if(addRecord({id:`usgs:${f.id}`,source:'USGS',type:'earthquake',title:f.properties?.title||'Earthquake',lat:c[1],lon:c[0],time:f.properties?.time||null,url:f.properties?.url||null,detail:`M${f.properties?.mag??'?'}`}))n++}setSource(id,'USGS earthquakes','LIVE',n,'M2.5+ · past day')}catch(e){setSource(id,'USGS earthquakes','FAILED',0,String(e.message||e))}}
async function pollEONET(){const id='eonet';setSource(id,'NASA EONET events','LOADING',0,'open natural events');try{const j=await getJSON('https://eonet.gsfc.nasa.gov/api/v3/events?status=open&limit=500');let n=0;for(const e of j.events||[]){const g=(e.geometry||[]).at(-1);if(!g)continue;let lat,lon;if(g.type==='Point'&&Array.isArray(g.coordinates)){lon=g.coordinates[0];lat=g.coordinates[1]}else{continue}if(addRecord({id:`eonet:${e.id}`,source:'NASA EONET',type:'hazard',title:e.title,lat,lon,time:g.date||null,url:(e.sources||[])[0]?.url||null,detail:(e.categories||[]).map(c=>c.title).join(', ')}))n++}setSource(id,'NASA EONET events','LIVE',n,'open point events')}catch(e){setSource(id,'NASA EONET events','FAILED',0,String(e.message||e))}}
async function pollNDBC(){const id='ndbc';setSource(id,'NOAA NDBC stations','LOADING',0,'active buoy/station inventory');try{const text=await getText('https://www.ndbc.noaa.gov/activestations.xml');const doc=new DOMParser().parseFromString(text,'application/xml');let n=0;for(const st of [...doc.querySelectorAll('station')]){const lat=Number(st.getAttribute('lat')),lon=Number(st.getAttribute('lon'));if(addRecord({id:`ndbc:${st.getAttribute('id')}`,source:'NOAA NDBC',type:'station',title:st.getAttribute('name')||st.getAttribute('id'),lat,lon,url:'https://www.ndbc.noaa.gov/',detail:'marine / meteorological station'}))n++}setSource(id,'NOAA NDBC stations','LIVE',n,'active inventory')}catch(e){setSource(id,'NOAA NDBC stations','FAILED',0,String(e.message||e))}}
async function pollCOOPS(){const id='coops';setSource(id,'NOAA CO-OPS stations','LOADING',0,'water-level stations');try{const j=await getJSON('https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations.json?type=waterlevels');let n=0;for(const st of j.stations||[]){if(addRecord({id:`coops:${st.id}`,source:'NOAA CO-OPS',type:'station',title:st.name||st.id,lat:st.lat,lon:st.lng,url:st.self||'https://tidesandcurrents.noaa.gov/',detail:'water level / tide station'}))n++}setSource(id,'NOAA CO-OPS stations','LIVE',n,'water-level stations')}catch(e){setSource(id,'NOAA CO-OPS stations','FAILED',0,String(e.message||e))}}
async function pollNWS(){const id='nws';setSource(id,'NOAA/NWS active alerts','LOADING',0,'official alert polygons/points');try{const j=await getJSON('https://api.weather.gov/alerts/active');let n=0;for(const f of j.features||[]){const c=f?.geometry?.coordinates;if(f?.geometry?.type!=='Point'||!Array.isArray(c))continue;if(addRecord({id:`nws:${f.id||crypto.randomUUID()}`,source:'NOAA/NWS',type:'alert',title:f.properties?.headline||f.properties?.event||'Active alert',lat:c[1],lon:c[0],time:f.properties?.sent||null,url:f.properties?.['@id']||null,detail:f.properties?.event||'alert'}))n++}setSource(id,'NOAA/NWS active alerts','LIVE',n,'point-geocoded alerts only on this Earth view')}catch(e){setSource(id,'NOAA/NWS active alerts','FAILED',0,String(e.message||e))}}
async function loadBroker(){const base=window.DOMSRuntimeConfig?.brokerUrl;if(!base){setSource('broker','D.O.M. observation broker','REGISTERED',0,'not configured in this deployment');return}setSource('broker','D.O.M. observation broker','LOADING',0,base);try{const j=await getJSON(`${base.replace(/\/$/,'')}/v1/observations`,15000);const rows=Array.isArray(j)?j:Array.isArray(j.records)?j.records:[];let n=0;for(const r of rows){const lat=r.latitude??r.lat,lon=r.longitude??r.lon;if(addRecord({id:`broker:${r.id||r.observationId||n}`,source:r.agency||r.network||r.sourceId||'D.O.M. broker',type:r.kind==='alert'?'alert':'station',title:r.title||r.name||r.stationName||r.sourceId||'Broker observation',lat,lon,time:r.observedAt||r.observed_at||null,url:r.sourceUrl||r.url||null,detail:r.variable?`${r.variable}${r.measurementValue!=null?`: ${r.measurementValue}${r.measurementUnit?` ${r.measurementUnit}`:''}`:''}`:(r.modality||r.platformClass||'broker record')}))n++}setSource('broker','D.O.M. observation broker','LIVE',n,base)}catch(e){setSource('broker','D.O.M. observation broker','FAILED',0,String(e.message||e))}}
async function refreshFabric(){clearRecords();await Promise.allSettled([pollUSGS(),pollEONET(),pollNDBC(),pollCOOPS(),pollNWS(),loadBroker()]);updateMap()}

function resetEarth(){map?.flyTo({center:[0,10],zoom:1.2,pitch:0,bearing:0,duration:800})}
function surfaceMode(){map?.flyTo({zoom:8,pitch:58,duration:900});const s=$('#providerState');if(s)s.textContent='Surface navigation mode · geographic web map only. This is not native room-scale AR.'}
function locateMe(){if(!navigator.geolocation){const s=$('#providerState');if(s)s.textContent='Browser geolocation unavailable.';return}navigator.geolocation.getCurrentPosition(pos=>{const c=[pos.coords.longitude,pos.coords.latitude];map?.flyTo({center:c,zoom:9,pitch:48,duration:900});const s=$('#providerState');if(s)s.textContent=`Centered on your permitted browser location · accuracy ≈ ${Math.round(pos.coords.accuracy)} m.`},err=>{const s=$('#providerState');if(s)s.textContent=`Location unavailable · ${err.message}`},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
function googleUrl(){const c=map?.getCenter();const z=Math.round(map?.getZoom()||2);return c?`https://www.google.com/maps/@${c.lat.toFixed(6)},${c.lng.toFixed(6)},${z}z`:'https://www.google.com/maps'}
function openGoogle(){window.open(googleUrl(),'_blank','noopener,noreferrer')}
function loadGoogleAPI(key){return new Promise((resolve,reject)=>{if(window.google?.maps)return resolve();const prev=document.querySelector('script[data-dom-google]');if(prev){prev.addEventListener('load',resolve,{once:true});prev.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.dataset.domGoogle='1';s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}`;s.async=true;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
function updateGoogleMarkers(){if(!googleMap||!window.google?.maps)return;googleMarkers.forEach(m=>m.setMap(null));googleMarkers=[];for(const r of records.slice(0,2500)){googleMarkers.push(new google.maps.Marker({position:{lat:r.lat,lng:r.lon},map:googleMap,title:r.title}))}}
async function toggleGoogle(){const key=window.DOMS_GOOGLE_MAPS_API_KEY;if(!key){const s=$('#providerState');if(s)s.textContent='Google in-page overlay requires a configured Maps JavaScript API key. The Open current view button remains available.';return}try{await loadGoogleAPI(key);let box=$('#googleMap');if(!box){box=document.createElement('div');box.id='googleMap';box.style.cssText='height:56vh;min-height:420px;border-radius:18px;overflow:hidden;margin-top:12px';$('#earthMap')?.insertAdjacentElement('afterend',box)}if(googleMap){box.remove();googleMap=null;googleMarkers=[];return}const c=map?.getCenter()||{lat:10,lng:0};googleMap=new google.maps.Map(box,{center:{lat:c.lat,lng:c.lng},zoom:Math.max(2,Math.round(map?.getZoom()||2)),mapTypeId:'satellite'});updateGoogleMarkers()}catch(e){const s=$('#providerState');if(s)s.textContent=`Google overlay failed: ${e.message||e}`}}

map=new maplibregl.Map({container:'earthMap',style:'https://demotiles.maplibre.org/globe.json',center:[0,10],zoom:1.2,attributionControl:true});
map.setProjection({type:'globe'});
map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'top-right');
map.on('load',()=>{installEarthImagery();installObservationLayers();refreshFabric();const s=$('#providerState');if(s)s.textContent='NASA Blue Marble geographic Earth active · source-backed D.O.M. observations remain anchored by latitude/longitude. Baseline imagery is not live.'});
map.on('click','dom-observations',e=>{const f=e.features?.[0];if(!f)return;const p=f.properties||{};new maplibregl.Popup().setLngLat(e.lngLat).setHTML(`<strong>${escapeHtml(p.title)}</strong><br><small>${escapeHtml(p.source)} · ${escapeHtml(p.detail)}</small>${p.time?`<br><small>${escapeHtml(p.time)}</small>`:''}${p.url?`<br><a target="_blank" rel="noopener noreferrer" href="${escapeHtml(p.url)}">official source ↗</a>`:''}`).addTo(map)});
map.on('click','dom-observation-clusters',async e=>{const feature=e.features?.[0],id=feature?.properties?.cluster_id,src=map.getSource('dom-observations');if(id==null||!src)return;const zoom=await src.getClusterExpansionZoom(id);map.easeTo({center:feature.geometry.coordinates,zoom})});
$('#resetEarth')?.addEventListener('click',resetEarth);
$('#earthImagery')?.addEventListener('click',toggleEarthImagery);
$('#surfaceMode')?.addEventListener('click',surfaceMode);
$('#locateMe')?.addEventListener('click',locateMe);
$('#googleOverlay')?.addEventListener('click',toggleGoogle);
$('#openGoogle')?.addEventListener('click',openGoogle);
setInterval(refreshFabric,300000);
window.DOMEarthRuntime=Object.freeze({refreshFabric,records:()=>records.slice(),sourceStates:()=>[...sourceStates.values()],validLatLon,googleUrl});
