import * as maplibregl from 'https://unpkg.com/maplibre-gl@6.6.0/dist/maplibre-gl.mjs';

const $=s=>document.querySelector(s);
const records=[];
const seen=new Set();
const state=new Map();
const OSM_STYLE={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]};
const colors={earthquake:'#5ae5ff',hazard:'#ffd43b',station:'#36e58b',alert:'#ff536f'};
const valid=(lat,lon)=>Number.isFinite(Number(lat))&&Number.isFinite(Number(lon))&&Number(lat)>=-90&&Number(lat)<=90&&Number(lon)>=-180&&Number(lon)<=180;
const safe=v=>String(v==null?'':v);
const esc=v=>safe(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function json(url,ms=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',signal:c.signal,headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return await r.json()}finally{clearTimeout(t)}}
async function text(url,ms=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return await r.text()}finally{clearTimeout(t)}}
function add(r){if(!r||!valid(r.lat,r.lon))return;const key=`${r.id||r.source}|${Number(r.lat).toFixed(6)}|${Number(r.lon).toFixed(6)}`;if(seen.has(key))return;seen.add(key);records.push({...r,lat:Number(r.lat),lon:Number(r.lon)})}
function setSource(id,label,status,count,detail=''){state.set(id,{label,status,count,detail});renderSources()}
function renderSources(){const box=$('#sourceFabric');if(!box)return;box.innerHTML=[...state.values()].map(s=>`<div class="source-row"><div><strong>${esc(s.label)}</strong><small>${esc(s.detail)}</small></div><strong class="${s.status==='LIVE'?'ok':s.status==='LOADING'?'loading':'fail'}">${esc(s.status)}${Number.isFinite(s.count)?` · ${s.count}`:''}</strong></div>`).join('')}
function geojson(){return{type:'FeatureCollection',features:records.map((r,i)=>({type:'Feature',id:i,geometry:{type:'Point',coordinates:[r.lon,r.lat]},properties:{title:r.title||r.source||'Observation',source:r.source||'Unknown',type:r.type||'station',detail:r.detail||'',time:r.time||'',url:r.url||'',lat:r.lat,lon:r.lon}}))}}
let map;
function paint(){const src=map?.getSource('dom-points');if(src)src.setData(geojson());const n=$('#earthCount');if(n)n.textContent=`${records.length.toLocaleString()} source-coordinate points loaded`}
async function pollUSGS(){setSource('usgs','USGS earthquakes','LOADING',0,'M2.5+ · past day');try{const j=await json('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson');let n=0;for(const f of j.features||[]){const c=f.geometry?.coordinates;if(!c)continue;add({id:`usgs:${f.id}`,source:'USGS',type:'earthquake',title:f.properties?.title,lat:c[1],lon:c[0],time:f.properties?.time,url:f.properties?.url,detail:`M${f.properties?.mag??'?'}`});n++}setSource('usgs','USGS earthquakes','LIVE',n,'M2.5+ · past day')}catch(e){setSource('usgs','USGS earthquakes','FAILED',0,e.message)}}
async function pollEONET(){setSource('eonet','NASA EONET','LOADING',0,'open natural events');try{const j=await json('https://eonet.gsfc.nasa.gov/api/v3/events?status=open&limit=500');let n=0;for(const e of j.events||[]){const g=(e.geometry||[]).at(-1);if(g?.type!=='Point'||!Array.isArray(g.coordinates))continue;add({id:`eonet:${e.id}`,source:'NASA EONET',type:'hazard',title:e.title,lat:g.coordinates[1],lon:g.coordinates[0],time:g.date,detail:(e.categories||[]).map(x=>x.title).join(', '),url:(e.sources||[])[0]?.url});n++}setSource('eonet','NASA EONET','LIVE',n,'open point events')}catch(e){setSource('eonet','NASA EONET','FAILED',0,e.message)}}
async function pollNDBC(){setSource('ndbc','NOAA NDBC stations','LOADING',0,'active station inventory');try{const x=await text('https://www.ndbc.noaa.gov/activestations.xml');const doc=new DOMParser().parseFromString(x,'application/xml');let n=0;for(const st of doc.querySelectorAll('station')){add({id:`ndbc:${st.getAttribute('id')}`,source:'NOAA NDBC',type:'station',title:st.getAttribute('name')||st.getAttribute('id'),lat:st.getAttribute('lat'),lon:st.getAttribute('lon'),detail:'marine / meteorological station inventory'});n++}setSource('ndbc','NOAA NDBC stations','LIVE',n,'active station inventory')}catch(e){setSource('ndbc','NOAA NDBC stations','FAILED',0,e.message)}}
async function pollCOOPS(){setSource('coops','NOAA CO-OPS stations','LOADING',0,'water-level station inventory');try{const j=await json('https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations.json?type=waterlevels');let n=0;for(const st of j.stations||[]){add({id:`coops:${st.id}`,source:'NOAA CO-OPS',type:'station',title:st.name||st.id,lat:st.lat,lon:st.lng,detail:'water-level station inventory'});n++}setSource('coops','NOAA CO-OPS stations','LIVE',n,'station inventory')}catch(e){setSource('coops','NOAA CO-OPS stations','FAILED',0,e.message)}}
async function pollNWS(){setSource('nws','NOAA/NWS alerts','LOADING',0,'point alerts only; polygons stay unplotted here');try{const j=await json('https://api.weather.gov/alerts/active');let n=0;for(const f of j.features||[]){const g=f.geometry,p=f.properties||{};if(g?.type!=='Point'||!Array.isArray(g.coordinates))continue;add({id:`nws:${f.id||p.id}`,source:'NOAA/NWS',type:'alert',title:p.headline||p.event,lat:g.coordinates[1],lon:g.coordinates[0],time:p.sent||p.effective,url:p['@id']||f.id,detail:p.event||'official alert'});n++}setSource('nws','NOAA/NWS alerts','LIVE',n,'source-coordinate point alerts')}catch(e){setSource('nws','NOAA/NWS alerts','FAILED',0,e.message)}}
async function refresh(){records.length=0;seen.clear();await Promise.allSettled([pollUSGS(),pollEONET(),pollNDBC(),pollCOOPS(),pollNWS()]);paint();const s=$('#providerState');if(s)s.textContent='Geographic Earth active · points use source-provided latitude/longitude. No AR client is claimed.'}
try{
  map=new maplibregl.Map({container:'earthMap',style:OSM_STYLE,center:[0,15],zoom:1.15,attributionControl:true,renderWorldCopies:false,antialias:false});
  map.setProjection({type:'globe'});
  map.addControl(new maplibregl.NavigationControl({showCompass:true,showZoom:true}),'top-right');
  map.on('load',()=>{map.addSource('dom-points',{type:'geojson',data:geojson()});map.addLayer({id:'dom-points-halo',type:'circle',source:'dom-points',paint:{'circle-color':['match',['get','type'],'earthquake',colors.earthquake,'hazard',colors.hazard,'alert',colors.alert,colors.station],'circle-radius':['match',['get','type'],'alert',10,'hazard',8,'earthquake',7,6],'circle-opacity':.18,'circle-blur':.65}});map.addLayer({id:'dom-points',type:'circle',source:'dom-points',paint:{'circle-color':['match',['get','type'],'earthquake',colors.earthquake,'hazard',colors.hazard,'alert',colors.alert,colors.station],'circle-radius':['match',['get','type'],'alert',6,'hazard',5,'earthquake',5,4],'circle-stroke-color':'#04131a','circle-stroke-width':1.2}});refresh()});
  map.on('click','dom-points',e=>{const f=e.features?.[0];if(!f)return;const p=f.properties||{},c=f.geometry.coordinates;new maplibregl.Popup({maxWidth:'300px'}).setLngLat(c).setHTML(`<strong>${esc(p.title)}</strong><br><small>${esc(p.source)} · ${esc(p.detail)}</small><br><small>${Number(c[1]).toFixed(5)}, ${Number(c[0]).toFixed(5)}</small>${p.time?`<br><small>${esc(p.time)}</small>`:''}`).addTo(map)});
  map.on('error',e=>{const s=$('#providerState');if(s)s.textContent=`Geographic map error: ${e?.error?.message||e?.message||'unknown error'}`});
}catch(e){const s=$('#providerState');if(s)s.textContent=`Geographic Earth failed to initialize: ${e.message||e}`}
$('#resetEarth')?.addEventListener('click',()=>map?.easeTo({center:[0,15],zoom:1.15,pitch:0,bearing:0,duration:400}));
$('#refreshEarth')?.addEventListener('click',refresh);
$('#locateMe')?.addEventListener('click',()=>navigator.geolocation?.getCurrentPosition(p=>map?.flyTo({center:[p.coords.longitude,p.coords.latitude],zoom:8,duration:700}),()=>{}));
