import * as THREE from 'https://unpkg.com/three@0.180.0/build/three.module.js';
const host=document.getElementById('earth3d'),state=document.getElementById('providerState'),stamp=document.getElementById('earthTimestamp');
const status=t=>{if(state)state.textContent=t};
const scene=new THREE.Scene();scene.background=new THREE.Color(0x000000);
const camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.z=3.15;
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.style.touchAction='none';host.prepend(renderer.domElement);
const globe=new THREE.Mesh(new THREE.SphereGeometry(1,160,112),new THREE.MeshBasicMaterial({color:0x102030}));scene.add(globe);
const glow=new THREE.Mesh(new THREE.SphereGeometry(1.012,128,96),new THREE.MeshBasicMaterial({color:0x7ec8ee,transparent:true,opacity:.045,side:THREE.BackSide,depthWrite:false}));scene.add(glow);
function size(){const r=host.getBoundingClientRect();const w=Math.max(1,r.width),h=Math.max(1,r.height);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(size).observe(host);size();
let dragging=false,lastX=0,lastY=0,lastDist=0;
const dist=t=>Math.hypot(t[0].clientX-t[1].clientX,t[0].clientY-t[1].clientY);
renderer.domElement.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId)});
renderer.domElement.addEventListener('pointermove',e=>{if(!dragging)return;globe.rotation.y+=(e.clientX-lastX)*.006;globe.rotation.x+=(e.clientY-lastY)*.004;glow.rotation.copy(globe.rotation);lastX=e.clientX;lastY=e.clientY});
renderer.domElement.addEventListener('pointerup',()=>dragging=false);renderer.domElement.addEventListener('pointercancel',()=>dragging=false);
renderer.domElement.addEventListener('touchstart',e=>{if(e.touches.length===2)lastDist=dist(e.touches)},{passive:true});renderer.domElement.addEventListener('touchmove',e=>{if(e.touches.length===2){const d=dist(e.touches);if(lastDist)camera.position.z=THREE.MathUtils.clamp(camera.position.z-(d-lastDist)*.006,1.55,6);lastDist=d}},{passive:true});
renderer.domElement.addEventListener('wheel',e=>{camera.position.z=THREE.MathUtils.clamp(camera.position.z+e.deltaY*.002,1.55,6)},{passive:true});
(function animate(){renderer.render(scene,camera);requestAnimationFrame(animate)})();
const GIBS='https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/VIIRS_SNPP_CorrectedReflectance_TrueColor/default';
const yesterday=()=>{const d=new Date(Date.now()-86400000);return d.toISOString().slice(0,10)};
function tileURL(date,z,x,y){return `${GIBS}/${date}/GoogleMapsCompatible_Level9/${z}/${y}/${x}.jpg`}
function loadImage(src){return new Promise((ok,no)=>{const im=new Image();im.crossOrigin='anonymous';im.onload=()=>ok(im);im.onerror=no;im.src=src})}
async function buildObservedTexture(date){const z=3,n=1<<z,tile=256,mosaic=document.createElement('canvas');mosaic.width=mosaic.height=n*tile;const mc=mosaic.getContext('2d');let loaded=0;await Promise.all(Array.from({length:n*n},async(_,i)=>{const x=i%n,y=Math.floor(i/n);try{const im=await loadImage(tileURL(date,z,x,y));mc.drawImage(im,x*tile,y*tile,tile,tile);loaded++}catch{}}));if(loaded<Math.floor(n*n*.7))throw Error(`satellite coverage tiles ${loaded}/${n*n}`);const out=document.createElement('canvas');out.width=2048;out.height=1024;const oc=out.getContext('2d');for(let py=0;py<out.height;py++){const lat=90-(py+.5)*180/out.height;const clamped=Math.max(-85.05112878,Math.min(85.05112878,lat));const rad=clamped*Math.PI/180;const my=(1-Math.log(Math.tan(rad)+1/Math.cos(rad))/Math.PI)/2*mosaic.height;oc.drawImage(mosaic,0,Math.max(0,Math.min(mosaic.height-1,my)),mosaic.width,1,0,py,out.width,1)}return new THREE.CanvasTexture(out)}
async function refresh(){const date=yesterday();status(`Building gap-free 3D observed Earth · NASA VIIRS ${date}…`);try{const t=await buildObservedTexture(date);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());if(globe.material.map)globe.material.map.dispose();globe.material.map=t;globe.material.color.set(0xffffff);globe.material.needsUpdate=true;stamp.textContent=`NASA VIIRS · ${date} daily observation context`;status(`Geographical Earth · 3D observed Earth · NASA VIIRS ${date} · spherical canvas texture`)}catch(e){status(`Observed Earth texture unavailable · ${e.message}`)}}
document.getElementById('refreshEarth')?.addEventListener('click',refresh);document.getElementById('resetEarth')?.addEventListener('click',()=>{camera.position.z=3.15;globe.rotation.set(0,0,0);glow.rotation.set(0,0,0)});refresh();