const $=s=>document.querySelector(s);const status=t=>{const e=$('#providerState');if(e)e.textContent=t};
const C=window.Cesium;if(!C)throw new Error('Cesium runtime did not load');
const viewer=new C.Viewer('earthCesium',{animation:false,timeline:false,baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,fullscreenButton:false,infoBox:false,selectionIndicator:false,requestRenderMode:false,baseLayer:false,terrainProvider:new C.EllipsoidTerrainProvider()});
viewer.scene.backgroundColor=C.Color.BLACK;viewer.scene.globe.baseColor=C.Color.fromCssColorString('#061522');viewer.scene.globe.showGroundAtmosphere=true;viewer.scene.globe.enableLighting=false;viewer.scene.skyAtmosphere.show=true;viewer.scene.fog.enabled=true;viewer.scene.globe.maximumScreenSpaceError=1.15;
const base=new C.UrlTemplateImageryProvider({url:'https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',credit:'Esri World Imagery',maximumLevel:19});const baseLayer=viewer.imageryLayers.addImageryProvider(base);baseLayer.alpha=1;
const labels=new C.UrlTemplateImageryProvider({url:'https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}',maximumLevel:19});const labelLayer=viewer.imageryLayers.addImageryProvider(labels);labelLayer.alpha=0;
/* VIIRS daily corrected-reflectance is a polar-orbit swath mosaic. Missing swaths are valid no-data, not globe geometry. Do not paint opaque no-data over the planet. Keep the complete photographic base authoritative until a transparent cloud-only/global composite is attached. */
const setDetail=()=>{const h=viewer.camera.positionCartographic.height;labelLayer.alpha=C.Math.clamp((900000-h)/700000,0,.92)};viewer.camera.changed.addEventListener(setDetail);viewer.camera.percentageChanged=.015;
viewer.camera.setView({destination:C.Cartesian3.fromDegrees(-35,12,18500000)});setDetail();status('Geographical Earth · complete globe surface · satellite geography continuous pole-to-pole · incomplete VIIRS swaths quarantined · live atmosphere pending transparent composite');
$('#resetEarth')?.addEventListener('click',()=>viewer.camera.flyTo({destination:C.Cartesian3.fromDegrees(-35,12,18500000),duration:.7}));$('#refreshEarth')?.addEventListener('click',()=>location.reload());$('#locateMe')?.addEventListener('click',()=>navigator.geolocation?.getCurrentPosition(p=>viewer.camera.flyTo({destination:C.Cartesian3.fromDegrees(p.coords.longitude,p.coords.latitude,4500),orientation:{heading:0,pitch:C.Math.toRadians(-55),roll:0},duration:1.2}),()=>status('Location unavailable.')));
