const $=s=>document.querySelector(s);const status=t=>{const e=$('#providerState');if(e)e.textContent=t};
const C=window.Cesium;if(!C)throw new Error('Cesium runtime did not load');
const viewer=new C.Viewer('earthCesium',{animation:false,timeline:false,baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,fullscreenButton:false,infoBox:false,selectionIndicator:false,requestRenderMode:false,baseLayer:false,terrainProvider:new C.EllipsoidTerrainProvider()});
viewer.scene.backgroundColor=C.Color.BLACK;viewer.scene.globe.baseColor=C.Color.fromCssColorString('#061522');viewer.scene.globe.showGroundAtmosphere=true;viewer.scene.globe.enableLighting=false;viewer.scene.skyAtmosphere.show=true;viewer.scene.fog.enabled=true;viewer.scene.globe.maximumScreenSpaceError=1.15;
const base=new C.UrlTemplateImageryProvider({url:'https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',credit:'Esri World Imagery',maximumLevel:19});const baseLayer=viewer.imageryLayers.addImageryProvider(base);baseLayer.alpha=1;
const labels=new C.UrlTemplateImageryProvider({url:'https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}',maximumLevel:19});const labelLayer=viewer.imageryLayers.addImageryProvider(labels);labelLayer.alpha=0;
const day=new Date(Date.now()-86400000).toISOString().slice(0,10);
const observationLayers=[];
const addObservation=(layerName,weight)=>{const p=new C.WebMapServiceImageryProvider({url:'https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi',layers:layerName,parameters:{service:'WMS',version:'1.1.1',request:'GetMap',styles:'',format:'image/png',transparent:true,time:day},credit:'NASA EOSDIS GIBS / VIIRS',tilingScheme:new C.GeographicTilingScheme(),rectangle:C.Rectangle.fromDegrees(-180,-90,180,90),minimumLevel:0,maximumLevel:6});const l=viewer.imageryLayers.addImageryProvider(p);l.alpha=0;l.brightness=1.02;l.contrast=1.02;let failures=0;p.errorEvent.addEventListener(()=>{failures++;if(failures>=2)l.show=false});observationLayers.push({layer:l,weight});};
/* Conservative fusion: three independent VIIRS platforms. PNG transparency preserves no-data; the permanent geographic globe always remains underneath. No generated pixels are labeled as observations. */
addObservation('VIIRS_SNPP_CorrectedReflectance_TrueColor',.34);
addObservation('VIIRS_NOAA20_CorrectedReflectance_TrueColor',.28);
addObservation('VIIRS_NOAA21_CorrectedReflectance_TrueColor',.24);
const setDetail=()=>{const h=viewer.camera.positionCartographic.height;const orbital=C.Math.clamp((h-1800000)/5000000,0,1);for(const o of observationLayers)o.layer.alpha=o.weight*orbital;labelLayer.alpha=C.Math.clamp((900000-h)/700000,0,.92)};viewer.camera.changed.addEventListener(setDetail);viewer.camera.percentageChanged=.015;
viewer.camera.setView({destination:C.Cartesian3.fromDegrees(-35,12,18500000)});setDetail();status(`Geographical Earth · complete base globe + conservative observed fusion · SNPP/NOAA-20/NOAA-21 VIIRS ${day} · no-data stays transparent · observations fade before ground view`);
$('#resetEarth')?.addEventListener('click',()=>viewer.camera.flyTo({destination:C.Cartesian3.fromDegrees(-35,12,18500000),duration:.7}));$('#refreshEarth')?.addEventListener('click',()=>location.reload());$('#locateMe')?.addEventListener('click',()=>navigator.geolocation?.getCurrentPosition(p=>viewer.camera.flyTo({destination:C.Cartesian3.fromDegrees(p.coords.longitude,p.coords.latitude,4500),orientation:{heading:0,pitch:C.Math.toRadians(-55),roll:0},duration:1.2}),()=>status('Location unavailable.')));
