const H={events:[],seen:new Set(),user:null};
const q=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function getJSON(url,ms=10000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:'application/json'}});if(!r.ok)throw Error(`${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function km(a,b,c,d){const R=6371,p=Math.PI/180,da=(c-a)*p,do_=(d-b)*p,x=Math.sin(da/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(do_/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function severity(e){if(e.kind==='Earthquake'){const m=Number(e.mag||0);if(m>=7)return'extreme';if(m>=6)return'high';if(m>=5)return'watch';return'info'}if(e.kind==='Severe Storm'){return/high|extreme|major|hurricane|typhoon|cyclone/i.test(e.title)?'high':'watch'}if(e.kind==='Wildfire'||e.kind==='Volcano')return'watch';return'info'}
function priority(e){let s={extreme:100,high:70,watch:40,info:10}[e.level]||0;const age=(Date.now()-new Date(e.time).getTime())/36e5;if(Number.isFinite(age))s+=Math.max(0,24-age);if(H.user&&Number.isFinite(e.lat)&&Number.isFinite(e.lon)){e.distance=km(H.user.lat,H.user.lon,e.lat,e.lon);if(e.distance<50)s+=35;else if(e.distance<200)s+=18;else if(e.distance<500)s+=8}return s}
function plot(e){if(!Number.isFinite(e.lat)||!Number.isFinite(e.lon))return'';const x=((e.lon+180)/360)*100,y=((90-e.lat)/180)*100;return `<span class="plot ${e.level}" title="${esc(e.title)}" style="left:${x}%;top:${y}%"></span>`}
function render(){H.events.forEach(e=>{e.level=severity(e);e.score=priority(e)});H.events.sort((a,b)=>b.score-a.score);q('#map').innerHTML='<div class="globe-grid"></div>'+H.events.slice(0,160).map(plot).join('');q('#events').innerHTML=H.events.slice(0,30).map(e=>`<div class="event-row"><strong class="${e.level==='extreme'?'danger':e.level==='high'?'warn':''}">${esc(e.level.toUpperCase())}</strong><div><strong>${esc(e.title)}</strong><div class="tiny">${esc(e.kind)} · ${new Date(e.time).toLocaleString()}${Number.isFinite(e.distance)?` · ${Math.round(e.distance)} km away`:''}</div></div><a target="_blank" rel="noopener" href="${esc(e.url||'#')}">Source →</a></div>`).join('')||'<p>No active events returned.</p>'}
async function loadUSGS(){const d=await getJSON('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson');const rows=(d.features||[]).map(f=>({id:'usgs:'+f.id,kind:'Earthquake',title:f.properties.place||'Earthquake',mag:f.properties.mag,time:new Date(f.properties.time).toISOString(),lat:f.geometry.coordinates[1],lon:f.geometry.coordinates[0],url:f.properties.url}));q('#quakeCount').textContent=rows.length;return rows}
async function loadEONET(){const d=await getJSON('https://eonet.gsfc.nasa.gov/api/v3/events?status=open&days=30&limit=250');const rows=[];const counts={storm:0,fire:0,volcano:0};for(const e of d.events||[]){const cats=(e.categories||[]).map(x=>String(x.id||x.title).toLowerCase());let kind=null;if(cats.some(x=>x.includes('severestorm')))kind='Severe Storm';else if(cats.some(x=>x.includes('wildfire')))kind='Wildfire';else if(cats.some(x=>x.includes('volcano')))kind='Volcano';if(!kind)continue;const g=(e.geometry||[]).at(-1)||{},co=g.coordinates||[];if(kind==='Severe Storm')counts.storm++;if(kind==='Wildfire')counts.fire++;if(kind==='Volcano')counts.volcano++;rows.push({id:'eonet:'+e.id,kind,title:e.title,time:g.date||new Date().toISOString(),lat:Array.isArray(co)&&typeof co[1]==='number'?co[1]:NaN,lon:Array.isArray(co)&&typeof co[0]==='number'?co[0]:NaN,url:(e.sources||[])[0]?.url||e.link})}q('#stormCount').textContent=counts.storm;q('#fireCount').textContent=counts.fire;q('#volcanoCount').textContent=counts.volcano;return rows}
async function loadNWS(){if(!H.user)return[];const d=await getJSON(`https://api.weather.gov/alerts/active?point=${H.user.lat},${H.user.lon}`);return(d.features||[]).map(f=>({id:'nws:'+f.id,kind:'Official Weather Alert',title:f.properties.event||'NWS Alert',time:f.properties.sent||new Date().toISOString(),lat:H.user.lat,lon:H.user.lon,url:f.properties['@id']||f.id,official:true,severityText:f.properties.severity||''}))}
function notifyNew(events){for(const e of events){if(H.seen.has(e.id))continue;H.seen.add(e.id);e.level=severity(e);priority(e);const nearby=Number.isFinite(e.distance)&&e.distance<=200;const urgent=e.level==='extreme'||(e.official&&/extreme|severe/i.test(e.severityText));if((nearby||urgent)&&document.hidden===false){if('vibrate'in navigator)navigator.vibrate([250,120,250]);if(Notification.permission==='granted')new Notification(`DOMS ${e.kind}`,{body:e.title,tag:e.id})}}}
async function refresh(){q('#sourceState').textContent='Refreshing USGS + NASA EONET'+(H.user?' + local NWS alerts':'')+'…';const jobs=[loadUSGS(),loadEONET()];if(H.user)jobs.push(loadNWS());const s=await Promise.allSettled(jobs),ok=s.filter(x=>x.status==='fulfilled');H.events=ok.flatMap(x=>x.value);notifyNew(H.events);render();q('#sourceState').textContent=`${ok.length}/${jobs.length} live feeds responded · ${H.events.length} normalized active records · updated ${new Date().toLocaleTimeString()}`}
async function enableLocal(){q('#localState').textContent='Requesting location…';if(!navigator.geolocation){q('#localState').textContent='Geolocation unavailable';return}navigator.geolocation.getCurrentPosition(async p=>{H.user={lat:p.coords.latitude,lon:p.coords.longitude};let n='visual alerts only';try{if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();if('Notification'in window&&Notification.permission==='granted')n='browser notifications enabled'}catch{}q('#localState').textContent=`Local awareness on · ${n}`;refresh()},()=>q('#localState').textContent='Location permission denied',{enableHighAccuracy:true,timeout:10000,maximumAge:300000})}
q('#refreshAll').addEventListener('click',refresh);q('#enableLocal').addEventListener('click',enableLocal);refresh();setInterval(refresh,60000);