const H={events:[],seen:new Set(),user:null,initialized:false,history:new Map(),feedHealth:new Map(),refreshing:false,refreshPending:false,refreshSeq:0,interval:null};
const q=s=>document.querySelector(s);const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=u=>{try{const x=new URL(String(u||''),location.href);return x.protocol==='https:'||x.protocol==='http:'?x.href:'#'}catch(_){return'#'}};
async function getJSON(url,ms=10000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${r.statusText}`);return await r.json()}finally{clearTimeout(t)}}
function clamp01(x){const n=Number(x);return Number.isFinite(n)?Math.max(0,Math.min(1,n)):0}
function finiteCoordinate(x){return x!==null&&x!==undefined&&x!==''&&Number.isFinite(Number(x))}
function validLatLon(lat,lon){return finiteCoordinate(lat)&&finiteCoordinate(lon)&&Number(lat)>=-90&&Number(lat)<=90&&Number(lon)>=-180&&Number(lon)<=180}
function normalizedTime(v){if(v===null||v===undefined||v==='')return null;const t=new Date(v).getTime();return Number.isFinite(t)?new Date(t).toISOString():null}
function timeLabel(v){const t=v==null?NaN:new Date(v).getTime();return Number.isFinite(t)?new Date(t).toLocaleString():'time unresolved'}
function km(a,b,c,d){if(!validLatLon(a,b)||!validLatLon(c,d))return Infinity;const R=6371,p=Math.PI/180,da=(Number(c)-Number(a))*p,dl=(Number(d)-Number(b))*p,x=Math.sin(da/2)**2+Math.cos(Number(a)*p)*Math.cos(Number(c)*p)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(Math.max(0,Math.min(1,x))))}
function sourceQuality(e){if(e.sourceType==='official-alert')return 1;if(e.sourceType==='observing-network')return .98;if(e.sourceType==='event-aggregation')return .84;if(e.authoritative)return .90;return .72}
function severity01(e){if(e.kind==='Earthquake'){const m=Number(e.mag);return Number.isFinite(m)?clamp01((m-3.5)/4):0}if(e.kind==='Tsunami'){const s=String(e.severityText||e.title||'').toLowerCase();if(s.includes('cancel'))return 0;if(s.includes('warning'))return .95;if(s.includes('advisory'))return .72;if(s.includes('watch'))return .62;return .35}if(e.kind==='Space Weather'){const s=String(e.severityText||e.title||''),m=s.match(/\b[GRS]([1-5])\b/i);return m?clamp01(.20+Number(m[1])*.16):.35}if(e.officialAlert){const s=String(e.severityText||'').toLowerCase();if(s==='extreme')return 1;if(s==='severe')return .82;if(s==='moderate')return .58;if(s==='minor')return .28}if(e.kind==='Severe Storm')return /hurricane|typhoon|cyclone|major|extreme/i.test(e.title||'')?.82:.58;if(e.kind==='Wildfire')return .58;if(e.kind==='Volcano')return .62;return .35}
function eventTimes(e={}){const explicit=normalizedTime(e.observedAt)||normalizedTime(e.observed_at)||null,published=normalizedTime(e.publishedAt)||normalizedTime(e.published_at)||normalizedTime(e.sent)||null,valid=normalizedTime(e.validAt)||normalizedTime(e.valid_at)||normalizedTime(e.effective)||normalizedTime(e.validTime)||null,expires=normalizedTime(e.expiresAt)||normalizedTime(e.expires_at)||normalizedTime(e.expires)||null,fetched=normalizedTime(e.fetchedAt)||normalizedTime(e.fetched_at)||normalizedTime(e.receivedAt)||null,legacy=!explicit&&!published&&!valid?normalizedTime(e.time):null;return{observedAt:explicit||legacy,publishedAt:published,validAt:valid,expiresAt:expires,fetchedAt:fetched,legacyTimeUsed:!!legacy}}
function temporalKind(e={}){const k=String(e.temporalKind||e.observationStatus||'').toLowerCase();if(k==='forecast'||k==='projection'||k==='modeled'||k==='model')return'model';if(e.officialAlert)return'publication';return'observation'}
function temporalReference(e={}){const t=eventTimes(e),k=temporalKind(e);if(k==='model')return t.validAt?{field:'validAt',time:t.validAt,t}:t.publishedAt?{field:'publishedAt',time:t.publishedAt,t}:t.observedAt?{field:'observedAt',time:t.observedAt,t}:{field:null,time:null,t};if(k==='publication')return t.publishedAt?{field:'publishedAt',time:t.publishedAt,t}:t.validAt?{field:'validAt',time:t.validAt,t}:t.observedAt?{field:'observedAt',time:t.observedAt,t}:{field:null,time:null,t};return t.observedAt?{field:'observedAt',time:t.observedAt,t}:t.publishedAt?{field:'publishedAt',time:t.publishedAt,t}:t.validAt?{field:'validAt',time:t.validAt,t}:{field:null,time:null,t}}
function temporalStatus(e={},now=Date.now()){const r=temporalReference(e),expiresMs=r.t.expiresAt?new Date(r.t.expiresAt).getTime():NaN;if(Number.isFinite(expiresMs)&&expiresMs<=now)return{...r,state:'EXPIRED',ageHours:null};if(!r.time)return{...r,state:'UNKNOWN',ageHours:null};const ms=new Date(r.time).getTime();if(!Number.isFinite(ms))return{...r,state:'UNKNOWN',ageHours:null};const ageHours=(now-ms)/36e5;if(ageHours<-(5/60))return{...r,state:'FUTURE VALID',ageHours};return{...r,state:'CURRENT',ageHours}}
function freshness01(e){const s=temporalStatus(e);if(s.state==='EXPIRED'||s.state==='UNKNOWN')return 0;if(s.state==='FUTURE VALID'){const lead=Math.max(0,-Number(s.ageHours||0));return clamp01(Math.exp(-lead/48))}const age=Math.max(0,Number(s.ageHours||0));return Math.exp(-age/24)}
function temporalSummary(e){const s=temporalStatus(e),t=s.t,parts=[];if(s.referenceField&&s.referenceTime)parts.push(`${s.referenceField} ${timeLabel(s.referenceTime)}`);else parts.push('source time unresolved');parts.push(s.state);if(t.fetchedAt)parts.push(`fetched ${timeLabel(t.fetchedAt)}`);return parts.join(' · ')}
function temporalSafeForAlert(e){const s=temporalStatus(e);if(s.state==='EXPIRED'||s.state==='UNKNOWN')return false;if(!s.referenceTime)return false;return true}
function proximity01(e){if(!H.user||!validLatLon(e.lat,e.lon))return 0;e.distance=km(H.user.lat,H.user.lon,e.lat,e.lon);return Number.isFinite(e.distance)?Math.exp(-e.distance/180):0}
function certainty01(e){if(!e.officialAlert)return e.observed===true?.85:.55;const c=String(e.certaintyText||'').toLowerCase();if(c==='observed')return 1;if(c==='likely')return .82;if(c==='possible')return .55;if(c==='unlikely')return .2;return .65}
function urgency01(e){if(!e.officialAlert)return freshness01(e);const u=String(e.urgencyText||'').toLowerCase();if(u==='immediate')return 1;if(u==='expected')return .82;if(u==='future')return .5;if(u==='past')return .1;return .6}
function geoQuality01(e){if(!validLatLon(e.lat,e.lon))return .15;const p=String(e.locationPrecision||'').toLowerCase();if(p==='source-coordinate'||p==='epicenter')return 1;if(p==='source-point')return .95;if(p==='alert-geometry-centroid')return .62;if(p==='event-geometry-point')return .78;if(p==='user-reference-point')return .35;return .65}
function correlationClass(e){const k=String(e.kind||'').toLowerCase();if(k==='earthquake')return'earthquake';if(k==='tsunami')return'tsunami';if(k==='space weather')return'space-weather';if(k==='severe storm')return'cyclone';if(k==='wildfire')return'wildfire';if(k==='volcano')return'volcano';if(k==='official weather alert'||e.officialAlert)return'official-weather-alert';return k||'unknown'}
function peerEvidence(e){if(!validLatLon(e.lat,e.lon))return[];const er=temporalReference(e);if(!er.time)return[];const out=[],klass=correlationClass(e);for(const x of H.events){if(x===e||correlationClass(x)!==klass||!validLatLon(x.lat,x.lon))continue;const xr=temporalReference(x);if(!xr.time)continue;const a=new Date(xr.time).getTime(),b=new Date(er.time).getTime();if(!Number.isFinite(a)||!Number.isFinite(b))continue;const dt=Math.abs(a-b)/36e5;if(dt<=12&&km(e.lat,e.lon,x.lat,x.lon)<=150)out.push(x)}return out}
function corroboration01(e){const rows=[e].concat(peerEvidence(e)).map(x=>({lineageId:x.lineageId||x.source||x.kind}));return window.DOMObservationModel?DOMObservationModel.corroboration(rows):clamp01((new Set(rows.map(x=>x.lineageId)).size-1)/3)}
function historyKey(e){return String(e.id||`${correlationClass(e)}:${validLatLon(e.lat,e.lon)?Math.round(Number(e.lat)):'x'}:${validLatLon(e.lat,e.lon)?Math.round(Number(e.lon)):'x'}`)}
function recordHistory(events){const now=Date.now();for(const e of events){const metric=severity01(e),key=historyKey(e),a=H.history.get(key)||[];a.push({t:now,v:metric});while(a.length>24)a.shift();H.history.set(key,a)}if(H.history.size>1500){for(const[k,a]of H.history){if(!a.length||now-a[a.length-1].t>86400000)H.history.delete(k);if(H.history.size<=1200)break}}}
function temporalTrend01(e){const a=H.history.get(historyKey(e))||[];if(a.length<3)return 0;const recent=a.slice(-6),first=recent[0].v,last=recent[recent.length-1].v,delta=last-first;if(delta<=0)return 0;return clamp01(delta/.35)}
function fallbackEqClass(m){m=Number(m);if(!Number.isFinite(m))return'unknown';if(m<2.5)return'micro/minor';if(m<4)return'minor';if(m<5)return'light';if(m<6)return'moderate';if(m<7)return'strong';if(m<8)return'major';return'great'}
function classify(e){let hazardClass=correlationClass(e),strength='unknown';if(e.kind==='Earthquake'){hazardClass='earthquake';strength=window.DOMHazardTaxonomy?DOMHazardTaxonomy.earthquakeClass(e.mag):fallbackEqClass(e.mag)}else if(e.kind==='Tsunami'){hazardClass='tsunami';strength=e.severityText||'official tsunami product'}else if(e.kind==='Space Weather'){hazardClass='space-weather';strength=e.severityText||'NOAA scale unresolved'}else if(e.kind==='Severe Storm'){hazardClass='cyclone';strength='not resolved from EONET alone'}else if(e.kind==='Wildfire'){hazardClass='wildfire';strength='not resolved from EONET alone'}else if(e.kind==='Volcano'){hazardClass='volcano';strength='not resolved from EONET alone'}else if(e.officialAlert){hazardClass='official-weather-alert';strength=e.severityText||'official severity unavailable'}return{hazardClass,strength}}
function evaluate(e){const cls=classify(e);e.hazardClass=cls.hazardClass;e.strengthClass=cls.strength;e.temporal=temporalStatus(e);const sev=severity01(e),quality=sourceQuality(e),fresh=freshness01(e),geo=geoQuality01(e),cert=certainty01(e),urg=urgency01(e),prox=proximity01(e),corr=corroboration01(e),trend=temporalTrend01(e),uncertaintyQuality=geo;const evidenceStrength=window.DOMObservationModel?DOMObservationModel.evidenceStrength({quality,freshness:fresh,geospatial:geo,corroboration:corr,uncertaintyQuality,trend}):clamp01(.24*quality+.18*fresh+.16*geo+.18*corr+.14*uncertaintyQuality+.10*trend);const hazard=clamp01(.55*sev+.20*urg+.10*prox+.10*corr+.05*trend);const decision=clamp01(.62*hazard+.38*evidenceStrength);const score=Math.round(decision*100),level=score>=86?'extreme':score>=70?'high':score>=52?'watch':'info';const evidenceGrade=window.DOMObservationModel?DOMObservationModel.evidenceGrade(evidenceStrength):'unrated';return{sev,quality,fresh,geo,cert,urg,prox,corr,trend,uncertaintyQuality,evidenceStrength,evidenceGrade,hazard,decision,score,level,temporal:e.temporal}}
function coords(e){return validLatLon(e.lat,e.lon)?`${Math.abs(Number(e.lat)).toFixed(2)}° ${Number(e.lat)>=0?'N':'S'}, ${Math.abs(Number(e.lon)).toFixed(2)}° ${Number(e.lon)>=0?'E':'W'}`:'location not resolved'}
function evidenceFor(e){const src=e.source||'source',signals=[];if(Number.isFinite(e.mag))signals.push(`magnitude ${Number(e.mag).toFixed(1)}`);if(e.strengthClass&&e.strengthClass!=='unknown')signals.push(`class ${e.strengthClass}`);if(e.officialAlert&&e.severityText)signals.push(`${e.severityText} official severity`);if(e.officialAlert&&e.certaintyText)signals.push(`${e.certaintyText} certainty`);if(e.officialAlert&&e.urgencyText)signals.push(`${e.urgencyText} urgency`);signals.push(`${Math.round(e.fresh*100)}% source-time freshness/relevance (${e.temporal?.state||'UNKNOWN'}${e.temporal?.referenceField?`, ${e.temporal.referenceField}`:''})`);signals.push(`${Math.round(e.evidenceStrength*100)}% evidence strength (${e.evidenceGrade})`);signals.push(`${Math.round(e.corr*100)}% same-hazard independent-lineage corroboration`);if(e.trend>0)signals.push(`${Math.round(e.trend*100)}% measured temporal worsening score`);const located=validLatLon(e.lat,e.lon),loc=coords(e),sourcePhrase=e.modality==='official-tsunami-product'?'The official tsunami center reports':e.kind==='Space Weather'?'The NOAA space-weather feed reports':e.sourceType==='event-aggregation'?'The event aggregation layer reports':e.modality==='official-warning'?'The official warning feed reports':'The observing network reports';const geoPhrase=located?`around ${loc}`:'with source geography unresolved';const interpretation=e.level==='extreme'||e.level==='high'?`${sourcePhrase} elevated ${e.kind.toLowerCase()} conditions ${geoPhrase}. Potential impacts depend on the hazard-specific footprint and current uncertainty.`:`${sourcePhrase} an active ${e.kind.toLowerCase()} signal ${geoPhrase}. Current evidence does not establish a stronger outcome.`;const caveat=e.officialAlert?'An official alert product is active; follow the linked authority for protective instructions and affected-area details.':'This is a research assessment, not an official warning or deterministic prediction.';return{headline:`${src}: ${e.title}.`,signals,interpretation,caveat,text:`${src}: ${e.title}. Evidence includes ${signals.join(', ')}. ${interpretation} Decision score ${e.score} out of 100. Evidence strength ${Math.round(e.evidenceStrength*100)} percent, ${e.evidenceGrade}. ${caveat}`}}
function isAlertEligible(e){const nearby=Number.isFinite(e.distance)&&e.distance<=250,temporalSafe=temporalSafeForAlert(e);const officialGate=temporalSafe&&e.officialAlert&&e.appliesToUser===true&&(/extreme|severe/i.test(e.severityText||''))&&(/observed|likely/i.test(e.certaintyText||''))&&(/immediate|expected/i.test(e.urgencyText||''));const fusionGate=temporalSafe&&nearby&&e.fresh>=.20&&e.decision>=.82&&e.evidenceStrength>=.72;return officialGate||fusionGate}
function plot(e){if(!validLatLon(e.lat,e.lon))return'';const x=((Number(e.lon)+180)/360)*100,y=((90-Number(e.lat))/180)*100;return `<span class="plot ${e.level}" title="${esc(e.title)}" style="left:${x}%;top:${y}%"></span>`}
function render(){H.events.forEach(e=>{Object.assign(e,evaluate(e));e.evidence=evidenceFor(e)});H.events.sort((a,b)=>b.score-a.score);const map=q('#map'),events=q('#events');if(map)map.innerHTML='<div class="globe-grid"></div>'+H.events.slice(0,160).map(plot).join('');if(events)events.innerHTML=H.events.slice(0,30).map((e,i)=>`<div class="event-row" data-event-index="${i}"><strong class="${e.level==='extreme'?'danger':e.level==='high'?'warn':''}">${esc(e.level.toUpperCase())}</strong><div><strong>${esc(e.title)}</strong><div class="tiny">${esc(e.kind)} · ${esc(e.strengthClass||'unclassified')} · ${esc(temporalSummary(e))}${Number.isFinite(e.distance)?` · ${Math.round(e.distance)} km away`:''} · score ${e.score}/100 · evidence ${Math.round(e.evidenceStrength*100)}% (${esc(e.evidenceGrade)})</div><div class="tiny">${esc(e.source||'Source')} · ${esc(e.modality||'unknown modality')} · ${esc(e.lineageId||'unknown lineage')}</div><div class="evidence-block"><strong>Evidence behind DOM voice</strong><div>${esc(e.evidence.headline)}</div><div class="tiny">Signals: ${esc(e.evidence.signals.join(' · '))}</div><div>${esc(e.evidence.interpretation)}</div><div class="tiny">${esc(e.evidence.caveat)}</div></div><button type="button" class="speak-event">Speak evidence</button> <button type="button" class="research-context" data-event-id="${esc(e.id)}">Research context</button><div class="research-context-out" id="research-${i}"></div></div><a target="_blank" rel="noopener noreferrer" href="${esc(safeUrl(e.url))}">Source →</a></div>`).join('')||'<p>No active events returned.</p>'}
function setText(sel,text){const n=q(sel);if(n)n.textContent=text}
async function loadUSGS(){const d=await getJSON('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson'),fetchedAt=new Date().toISOString();const rows=[];for(const f of d.features||[]){if(!f||!f.id)continue;const co=f.geometry&&Array.isArray(f.geometry.coordinates)?f.geometry.coordinates:null,p=f.properties||{};if(!co||!validLatLon(co[1],co[0]))continue;const observedAt=Number.isFinite(Number(p.time))?new Date(Number(p.time)).toISOString():null;rows.push({id:'usgs:'+f.id,kind:'Earthquake',source:'USGS',sourceType:'observing-network',lineageId:'usgs-comcat',modality:'seismic',authoritative:true,officialAlert:false,observed:true,title:p.place||'Earthquake',mag:Number.isFinite(Number(p.mag))?Number(p.mag):NaN,time:observedAt,observedAt,fetchedAt,temporalKind:'observation',lat:Number(co[1]),lon:Number(co[0]),locationPrecision:'epicenter',url:p.url})}setText('#quakeCount',rows.length);return rows}
async function loadEONET(){const d=await getJSON('https://eonet.gsfc.nasa.gov/api/v3/events?status=open&days=30&limit=250'),fetchedAt=new Date().toISOString();const rows=[],counts={storm:0,fire:0,volcano:0};for(const e of d.events||[]){if(!e||!e.id)continue;const cats=(e.categories||[]).map(x=>String(x.id||x.title).toLowerCase());let kind=null;if(cats.some(x=>x.includes('severestorm')))kind='Severe Storm';else if(cats.some(x=>x.includes('wildfire')))kind='Wildfire';else if(cats.some(x=>x.includes('volcano')))kind='Volcano';if(!kind)continue;const gs=e.geometry||[],g=gs.length?gs[gs.length-1]:{},co=g.coordinates||[];if(kind==='Severe Storm')counts.storm++;if(kind==='Wildfire')counts.fire++;if(kind==='Volcano')counts.volcano++;const sources=e.sources||[],u=sources.length&&sources[0].url?sources[0].url:e.link,observedAt=normalizedTime(g.date);const ok=Array.isArray(co)&&validLatLon(co[1],co[0]);rows.push({id:'eonet:'+e.id,kind,source:'NASA EONET',sourceType:'event-aggregation',lineageId:'nasa-eonet',modality:'event-aggregation',authoritative:true,officialAlert:false,observed:false,title:e.title||kind,time:observedAt,observedAt,fetchedAt,temporalKind:'observation',lat:ok?Number(co[1]):NaN,lon:ok?Number(co[0]):NaN,locationPrecision:ok?'event-geometry-point':'unresolved',geometry:g,url:u})}setText('#stormCount',counts.storm);setText('#fireCount',counts.fire);setText('#volcanoCount',counts.volcano);return rows}
function geometryCentroid(geom){if(!geom||!geom.type||!geom.coordinates)return null;const pts=[];const walk=x=>{if(Array.isArray(x)&&x.length>=2&&finiteCoordinate(x[0])&&finiteCoordinate(x[1])){const lon=Number(x[0]),lat=Number(x[1]);if(validLatLon(lat,lon))pts.push([lon,lat]);return}if(Array.isArray(x))x.forEach(walk)};walk(geom.coordinates);if(!pts.length)return null;let lat=0,sinLon=0,cosLon=0;for(const p of pts){lat+=p[1];const r=p[0]*Math.PI/180;sinLon+=Math.sin(r);cosLon+=Math.cos(r)}lat/=pts.length;let lon=Math.atan2(sinLon,cosLon)*180/Math.PI;if(lon>180)lon-=360;if(lon<-180)lon+=360;return validLatLon(lat,lon)?{lat,lon}:null}
async function loadNWS(){if(!H.user)return[];const d=await getJSON(`https://api.weather.gov/alerts/active?point=${H.user.lat},${H.user.lon}`),fetchedAt=new Date().toISOString();return(d.features||[]).map(f=>{if(!f||!f.id)return null;const p=f.properties||{},c=geometryCentroid(f.geometry),publishedAt=normalizedTime(p.sent),validAt=normalizedTime(p.effective||p.onset),expiresAt=normalizedTime(p.expires);return{id:'nws:'+f.id,kind:'Official Weather Alert',source:'NWS',sourceType:'official-alert',lineageId:'nws-cap',modality:'official-warning',authoritative:true,officialAlert:true,appliesToUser:true,observed:String(p.certainty||'').toLowerCase()==='observed',title:p.event||'NWS Alert',time:publishedAt,observedAt:null,publishedAt,validAt,expiresAt,fetchedAt,temporalKind:'publication',lat:c?c.lat:NaN,lon:c?c.lon:NaN,locationPrecision:c?'alert-geometry-centroid':'unresolved',geometry:f.geometry||null,url:p['@id']||f.id,severityText:p.severity||'',certaintyText:p.certainty||'',urgencyText:p.urgency||''}}).filter(Boolean)}
function trimSeen(){if(H.seen.size<=10000)return;const drop=H.seen.size-7000;let i=0;for(const id of H.seen){H.seen.delete(id);if(++i>=drop)break}}
function notifyNew(events){if(!H.initialized){events.forEach(e=>H.seen.add(e.id));trimSeen();H.initialized=true;return}for(const e of events){if(H.seen.has(e.id))continue;H.seen.add(e.id);Object.assign(e,evaluate(e));e.evidence=evidenceFor(e);if(!isAlertEligible(e))continue;if('vibrate'in navigator){try{navigator.vibrate([250,120,250])}catch(_){ }}if('Notification'in window&&Notification.permission==='granted'){try{new Notification(`DOM ${e.kind}`,{body:`${e.title} · score ${e.score}/100 · evidence ${Math.round(e.evidenceStrength*100)}%`,tag:e.id})}catch(_){ }}if(window.DOMSHazardVoice)DOMSHazardVoice.announce(e)}trimSeen()}
function dispatchRefresh(detail){try{window.dispatchEvent(new CustomEvent('dom:hazard-refresh',{detail}))}catch(_){ }}
async function refresh(){if(H.refreshing){H.refreshPending=true;return}H.refreshing=true;H.refreshPending=false;const seq=++H.refreshSeq;setText('#sourceState','Refreshing authoritative feeds…');const defs=[{name:'USGS',run:loadUSGS},{name:'NASA EONET',run:loadEONET}];if(H.user)defs.push({name:'NWS local alerts',run:loadNWS});try{const started=performance.now(),s=await Promise.allSettled(defs.map(d=>d.run())),rows=[];let ok=0;const failed=[];s.forEach((r,i)=>{const name=defs[i].name;if(r.status==='fulfilled'){ok++;H.feedHealth.set(name,{ok:true,checkedAt:Date.now()});rows.push.apply(rows,r.value)}else{failed.push(name);H.feedHealth.set(name,{ok:false,checkedAt:Date.now(),error:String(r.reason&&r.reason.message||r.reason||'failed')})}});if(seq!==H.refreshSeq)return;H.events=rows;recordHistory(H.events);notifyNew(H.events);render();const elapsed=Math.round(performance.now()-started);setText('#sourceState',`${ok}/${defs.length} configured feeds responded · ${H.events.length} normalized active records · ${elapsed} ms · browser refresh ${new Date().toLocaleTimeString()}${failed.length?` · unavailable: ${failed.join(', ')}`:''}. Feed response time is not event freshness.`);dispatchRefresh({ok,total:defs.length,failed,elapsedMs:elapsed,eventCount:H.events.length,events:H.events,feedHealth:[...H.feedHealth.entries()]})}finally{H.refreshing=false;if(H.refreshPending){H.refreshPending=false;setTimeout(refresh,0)}}}
async function enableLocal(){setText('#localState','Requesting location…');if(!navigator.geolocation){setText('#localState','Geolocation unavailable');return}navigator.geolocation.getCurrentPosition(async p=>{if(!p||!p.coords||!validLatLon(p.coords.latitude,p.coords.longitude)){setText('#localState','Location unavailable');return}H.user={lat:Number(p.coords.latitude),lon:Number(p.coords.longitude)};let n='visual alerts only';try{if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();if('Notification'in window&&Notification.permission==='granted')n='browser notifications enabled'}catch(_){ }setText('#localState',`Local awareness on · ${n}`);refresh()},()=>setText('#localState','Location permission denied'),{enableHighAccuracy:true,timeout:10000,maximumAge:300000})}
const eventsNode=q('#events');if(eventsNode)eventsNode.addEventListener('click',async ev=>{const row=ev.target.closest('.event-row'),idx=Number(row&&row.dataset.eventIndex),e=Number.isInteger(idx)?H.events[idx]:null;if(ev.target.closest('.speak-event')){if(window.DOMSHazardVoice&&e)DOMSHazardVoice.describe(e);return}const b=ev.target.closest('.research-context');if(!b||!window.DOMSHazardResearch)return;const out=row&&row.querySelector('.research-context-out');if(!e||!out)return;b.disabled=true;out.innerHTML='<div class="tiny">Searching DOMS research federation…</div>';try{const ctx=await DOMSHazardResearch.contextForEvent(e);out.innerHTML=DOMSHazardResearch.render(ctx)}catch(_){out.innerHTML='<div class="tiny">Research context unavailable right now.</div>'}finally{b.disabled=false}});
const voiceOn=q('#voiceOn'),voiceMute=q('#voiceMute'),voiceState=q('#voiceState');if(voiceOn)voiceOn.addEventListener('click',()=>{if(!window.DOMSHazardVoice){if(voiceState)voiceState.textContent='DOM voice module unavailable';return}const s=DOMSHazardVoice.enable();if(voiceState)voiceState.textContent=s.message});if(voiceMute)voiceMute.addEventListener('click',()=>{if(!window.DOMSHazardVoice){if(voiceState)voiceState.textContent='DOM voice module unavailable';return}const now=DOMSHazardVoice.state(),muted=DOMSHazardVoice.mute(!now.muted);voiceMute.textContent=muted?'Unmute DOM':'Mute DOM';if(voiceState)voiceState.textContent=muted?'DOM voice muted':'DOM voice on'});
const refreshBtn=q('#refreshAll'),localBtn=q('#enableLocal');if(refreshBtn)refreshBtn.addEventListener('click',refresh);if(localBtn)localBtn.addEventListener('click',enableLocal);refresh();H.interval=setInterval(()=>{if(document.visibilityState==='visible')refresh()},60000);window.addEventListener('pagehide',()=>{if(H.interval)clearInterval(H.interval);if(window.DOMSHazardVoice)DOMSHazardVoice.stop()},{once:true});