const H={events:[],seen:new Set(),user:null,history:loadHistory()};
const q=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function getJSON(url,ms=10000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:'application/json'}});if(!r.ok)throw Error(`${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function clamp(x,a=0,b=1){return Math.max(a,Math.min(b,x))}function logistic(x,k=8,m=.5){return 1/(1+Math.exp(-k*(x-m)))}
function km(a,b,c,d){const R=6371,p=Math.PI/180,da=(c-a)*p,do_=(d-b)*p,x=Math.sin(da/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(do_/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function loadHistory(){try{return JSON.parse(localStorage.getItem('domsHazardHistory')||'{}')}catch{return{}}}function saveHistory(){try{localStorage.setItem('domsHazardHistory',JSON.stringify(H.history))}catch{}}
const REL={USGS:.98,NWS:.99,'NASA EONET':.92,'NASA FIRMS':.95,OTHER:.75};
function ageHours(e){const v=(Date.now()-new Date(e.time).getTime())/36e5;return Number.isFinite(v)?Math.max(0,v):999}
function sourceReliability(e){return REL[e.source]??REL.OTHER}
function hazardSeverity(e){if(e.kind==='Earthquake'){const m=Number(e.mag);return Number.isFinite(m)?clamp((m-3.5)/4):.25}if(e.official){const s=String(e.severityText||'').toLowerCase();return({extreme:1,severe:.82,moderate:.58,minor:.28,unknown:.4}[s]??.4)}if(e.kind==='Severe Storm'){return /category 5|extreme|super typhoon/i.test(e.title)?1:/category 4|major hurricane|violent/i.test(e.title)?.9:/hurricane|typhoon|cyclone|severe/i.test(e.title)?.72:.48}if(e.kind==='Wildfire')return .58;if(e.kind==='Volcano')return .62;return .35}
function certaintyWeight(e){if(!e.official)return .65;const v=String(e.certainty||'').toLowerCase();return({observed:1,likely:.82,possible:.58,unlikely:.25,unknown:.45}[v]??.45)}
function urgencyWeight(e){if(!e.official)return clamp(1-ageHours(e)/72);const v=String(e.urgency||'').toLowerCase();return({immediate:1,expected:.82,future:.55,past:.1,unknown:.4}[v]??.4)}
function freshness(e){return Math.exp(-ageHours(e)/24)}
function geoQuality(e){if(!Number.isFinite(e.lat)||!Number.isFinite(e.lon))return .2;return e.official?.95:.82}
function corroborate(events){for(const e of events){let n=0;for(const x of events){if(x===e||x.kind!==e.kind||x.source===e.source)continue;if(![e.lat,e.lon,x.lat,x.lon].every(Number.isFinite))continue;const d=km(e.lat,e.lon,x.lat,x.lon),dt=Math.abs(new Date(e.time)-new Date(x.time))/36e5;if(d<=75&&dt<=12)n++}e.corroboration=n;e.corroborationWeight=clamp(n/3)}}
function proximity(e){if(!H.user||!Number.isFinite(e.lat)||!Number.isFinite(e.lon))return 0;e.distance=km(H.user.lat,H.user.lon,e.lat,e.lon);return Math.exp(-e.distance/180)}
function momentum(e){const key=`${e.kind}:${Math.round((e.lat||0)*2)/2}:${Math.round((e.lon||0)*2)/2}`;const prev=H.history[key],now=Date.now();H.history[key]={t:now,s:hazardSeverity(e)};if(!prev)return 0;const dt=(now-prev.t)/36e5;if(dt<=0||dt>24)return 0;return clamp((hazardSeverity(e)-Number(prev.s||0))/.35)}
function evaluate(e){const sev=hazardSeverity(e),rel=sourceReliability(e),fq=freshness(e),gq=geoQuality(e),cor=e.corroborationWeight||0,cert=certaintyWeight(e),urg=urgencyWeight(e),prox=proximity(e),mom=momentum(e);const confidence=clamp(.30*rel+.18*fq+.12*gq+.18*cert+.12*cor+.10*(1-Math.min(ageHours(e),24)/24));const hazard=clamp(.55*sev+.20*urg+.10*prox+.10*cor+.05*mom);const decision=clamp(.62*hazard+.38*confidence);e.math={sev,rel,fq,gq,cor,cert,urg,prox,mom,confidence,hazard,decision};e.level=decision>=.86?'extreme':decision>=.70?'high':decision>=.52?'watch':'info';e.score=Math.round(decision*100);return e}
function plot(e){if(!Number.isFinite(e.lat)||!Number.isFinite(e.lon))return'';const x=((e.lon+180)/360)*100,y=((90-e.lat)/180)*100;return `<span class="plot ${e.level}" title="${esc(e.title)} · ${e.score}/100" style="left:${x}%;top:${y}%"></span>`}
function render(){corroborate(H.events);H.events.forEach(e=>evaluate(e));saveHistory();H.events.sort((a,b)=>b.score-a.score||new Date(b.time)-new Date(a.time));q('#map').innerHTML='<div class="globe-grid"></div>'+H.events.slice(0,200).map(plot).join('');q('#events').innerHTML=H.events.slice(0,40).map(e=>`<div class="event-row"><strong class="${e.level==='extreme'?'danger':e.level==='high'?'warn':''}">${esc(e.level.toUpperCase())} ${e.score}</strong><div><strong>${esc(e.title)}</strong><div class="tiny">${esc(e.kind)} · ${new Date(e.time).toLocaleString()}${Number.isFinite(e.distance)?` · ${Math.round(e.distance)} km away`:''} · confidence ${Math.round(e.math.confidence*100)}%${e.corroboration?` · ${e.corroboration+1} independent feeds`:''}</div></div><a target="_blank" rel="noopener" href="${esc(e.url||'#')}">Source →</a></div>`).join('')||'<p>No active events returned.</p>'}
async function loadUSGS(){const d=await getJSON('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson');const rows=(d.features||[]).map(f=>({id:'usgs:'+f.id,source:'USGS',kind:'Earthquake',title:f.properties.place||'Earthquake',mag:f.properties.mag,time:new Date(f.properties.time).toISOString(),lat:f.geometry.coordinates[1],lon:f.geometry.coordinates[0],url:f.properties.url,official:true,certainty:'Observed',urgency:'Immediate'}));q('#quakeCount').textContent=rows.length;return rows}
async function loadEONET(){const d=await getJSON('https://eonet.gsfc.nasa.gov/api/v3/events?status=open&days=30&limit=250');const rows=[],counts={storm:0,fire:0,volcano:0};for(const e of d.events||[]){const cats=(e.categories||[]).map(x=>String(x.id||x.title).toLowerCase());let kind=null;if(cats.some(x=>x.includes('severestorm')))kind='Severe Storm';else if(cats.some(x=>x.includes('wildfire')))kind='Wildfire';else if(cats.some(x=>x.includes('volcano')))kind='Volcano';if(!kind)continue;const g=(e.geometry||[]).at(-1)||{},co=g.coordinates||[];if(kind==='Severe Storm')counts.storm++;if(kind==='Wildfire')counts.fire++;if(kind==='Volcano')counts.volcano++;rows.push({id:'eonet:'+e.id,source:'NASA EONET',kind,title:e.title,time:g.date||new Date().toISOString(),lat:Array.isArray(co)&&typeof co[1]==='number'?co[1]:NaN,lon:Array.isArray(co)&&typeof co[0]==='number'?co[0]:NaN,url:(e.sources||[])[0]?.url||e.link})}q('#stormCount').textContent=counts.storm;q('#fireCount').textContent=counts.fire;q('#volcanoCount').textContent=counts.volcano;return rows}
async function loadNWS(){if(!H.user)return[];const d=await getJSON(`https://api.weather.gov/alerts/active?point=${H.user.lat},${H.user.lon}`);return(d.features||[]).map(f=>({id:'nws:'+f.id,source:'NWS',kind:'Official Weather Alert',title:f.properties.event||'NWS Alert',time:f.properties.sent||new Date().toISOString(),lat:H.user.lat,lon:H.user.lon,url:f.properties['@id']||f.id,official:true,severityText:f.properties.severity||'',certainty:f.properties.certainty||'',urgency:f.properties.urgency||''}))}
function shouldNotify(e){evaluate(e);const nearby=Number.isFinite(e.distance)&&e.distance<=250;const officialCritical=e.official&&(/extreme|severe/i.test(e.severityText)||/observed/i.test(e.certainty))&&/immediate|expected/i.test(e.urgency||'Immediate');return officialCritical||(nearby&&e.math.decision>=.82&&e.math.confidence>=.72)}
function notifyNew(events){for(const e of events){if(H.seen.has(e.id))continue;H.seen.add(e.id);if(!shouldNotify(e))continue;if('vibrate'in navigator)navigator.vibrate([300,120,300,120,500]);if('Notification'in window&&Notification.permission==='granted')new Notification(`DOMS ${e.kind}`,{body:`${e.title} · decision ${e.score}/100`,tag:e.id})}}
async function refresh(){q('#sourceState').textContent='Refreshing USGS + NASA EONET'+(H.user?' + local NWS alerts':'')+'…';const jobs=[loadUSGS(),loadEONET()];if(H.user)jobs.push(loadNWS());const s=await Promise.allSettled(jobs),ok=s.filter(x=>x.status==='fulfilled');H.events=ok.flatMap(x=>x.value);corroborate(H.events);notifyNew(H.events);render();q('#sourceState').textContent=`${ok.length}/${jobs.length} live feeds responded · ${H.events.length} normalized records · probabilistic decision model v2 · updated ${new Date().toLocaleTimeString()}`}
async function enableLocal(){q('#localState').textContent='Requesting location…';if(!navigator.geolocation){q('#localState').textContent='Geolocation unavailable';return}navigator.geolocation.getCurrentPosition(async p=>{H.user={lat:p.coords.latitude,lon:p.coords.longitude};let n='visual alerts only';try{if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();if('Notification'in window&&Notification.permission==='granted')n='browser notifications enabled'}catch{}q('#localState').textContent=`Local awareness on · ${n}`;refresh()},()=>q('#localState').textContent='Location permission denied',{enableHighAccuracy:true,timeout:10000,maximumAge:300000})}
q('#refreshAll').addEventListener('click',refresh);q('#enableLocal').addEventListener('click',enableLocal);refresh();setInterval(refresh,60000);